"""
API Testing Question Bank
Senior/architect-level REST API testing questions - HTTP fundamentals,
framework/environment configuration, dynamic content validation,
response body/header/cookie validation, realistic dynamic test data,
and end-to-end authentication/token/session lifecycle across a full
CRUD flow. Tool-specific sub-banks (Rest Assured for Java, Postman for
manual testing, Playwright's APIRequestContext for JS/TS/Python) are
blended in based on which skills the candidate selected.
"""

import random
from typing import Dict, List


CORE_API_QUESTIONS: List[Dict] = [
    # HTTP / REST fundamentals
    {"id": "api_core_001", "question": "Walk through the main HTTP status code classes (1xx-5xx) and give a realistic example of when each would be returned by an API.", "expected_answer": "1xx informational (rare in APIs), 2xx success (200 OK, 201 Created), 3xx redirection, 4xx client error (400 bad request, 404 not found), 5xx server error (500 internal error, 503 unavailable) - distinguishing client-caused vs server-caused failures.", "difficulty": "Basic", "category": "fundamentals"},
    {"id": "api_core_002", "question": "What's the difference between a 401 Unauthorized and a 403 Forbidden response, and how would you test both?", "expected_answer": "401 means authentication is missing/invalid (no valid identity); 403 means the identity is known but lacks permission for that resource. Test 401 by omitting/corrupting the token; test 403 by authenticating as a user without the required role/permission.", "difficulty": "Intermediate", "category": "fundamentals"},
    {"id": "api_core_003", "question": "What's the difference between 200, 201, 202, and 204 responses in a REST API, and which would you expect from POST, PUT, and DELETE respectively?", "expected_answer": "200 OK (generic success with body), 201 Created (POST that created a resource, typically with a Location header), 202 Accepted (request accepted for async processing), 204 No Content (success with no body, common for DELETE or some PUT/PATCH operations).", "difficulty": "Intermediate", "category": "fundamentals"},
    {"id": "api_core_004", "question": "What is idempotency in REST APIs? Which HTTP methods are idempotent and which aren't, and why does that matter for test design?", "expected_answer": "An idempotent operation produces the same result no matter how many times it's repeated. GET, PUT, DELETE are idempotent; POST is not. Tests should verify repeated PUT/DELETE calls don't cause unintended side effects, while repeated POSTs are expected to create duplicates unless explicitly guarded (e.g. idempotency keys).", "difficulty": "Advanced", "category": "fundamentals"},
    {"id": "api_core_005", "question": "What's the practical difference between PUT and PATCH, and how would you test that an API correctly implements each?", "expected_answer": "PUT replaces the entire resource (fields omitted may be reset/nulled); PATCH applies a partial update (only specified fields change). Test PUT by sending a full payload and verifying untouched fields reset/remain per spec; test PATCH by sending a subset and verifying other fields are untouched.", "difficulty": "Intermediate", "category": "fundamentals"},
    {"id": "api_core_006", "question": "What's the difference between a 400 Bad Request and a 422 Unprocessable Entity?", "expected_answer": "400 typically means the request is malformed (invalid JSON, wrong type); 422 means the request is well-formed but fails semantic/business validation (e.g. a required field is present but violates a business rule). Many APIs conflate the two, which is itself worth testing for consistency.", "difficulty": "Advanced", "category": "fundamentals"},
    {"id": "api_core_007", "question": "What are the components of a well-formed REST API request you'd account for in test design (method, URL, headers, query params, body)?", "expected_answer": "HTTP method, full URL including path/query parameters, required and optional headers (Content-Type, Accept, Authorization), and request body schema - each is a separate axis for boundary/negative testing.", "difficulty": "Basic", "category": "fundamentals"},
    {"id": "api_core_008", "question": "What is API versioning, and what strategies exist for it (URL path, custom header, query param, content negotiation)?", "expected_answer": "Versioning lets an API evolve without breaking existing clients. Strategies: URL path (/v1/users), custom header (Api-Version: 1), query param (?version=1), or Accept header content negotiation (application/vnd.company.v1+json) - each has different testing and backward-compatibility implications.", "difficulty": "Advanced", "category": "fundamentals"},
    {"id": "api_core_009", "question": "How would you test that an API correctly enforces required vs optional fields in a request payload?", "expected_answer": "Systematically omit each required field one at a time and assert a 400/422 with a clear error message; omit optional fields and assert the request still succeeds with sensible defaults.", "difficulty": "Intermediate", "category": "coding_problem"},
    {"id": "api_core_010", "question": "What's the difference between synchronous and asynchronous REST APIs, and how would you test an endpoint that triggers a long-running background job?", "expected_answer": "Synchronous APIs return the final result in the response; asynchronous ones return a 202 Accepted with a job/status URL, requiring the test to poll (or listen on a webhook/callback) until the job completes, then validate the final state.", "difficulty": "Advanced", "category": "scenario"},

    # Framework / configuration / base URL management
    {"id": "api_core_011", "question": "How do you manage base URLs across different environments (dev/QA/staging/prod) in an API test automation framework?", "expected_answer": "Externalize base URL into environment-specific config files or environment variables read at runtime, never hard-coded in test logic, so the same suite runs unmodified against any environment by switching a config flag.", "difficulty": "Intermediate", "category": "tool"},
    {"id": "api_core_012", "question": "What's the risk of hard-coding a base URL (or credentials) directly inside test scripts?", "expected_answer": "Makes the suite unable to run against multiple environments without code changes, risks accidentally hitting production, and often leaks secrets into version control.", "difficulty": "Basic", "category": "fundamentals"},
    {"id": "api_core_013", "question": "How would you design a configuration layer for an API test framework to support multiple environments without code changes?", "expected_answer": "A config resolver that loads environment-specific values (base URL, credentials, feature flags) from files/env vars keyed by an environment name passed at runtime (e.g. via a CLI flag or CI variable), with a shared base configuration and per-environment overrides.", "difficulty": "Advanced", "category": "scenario"},
    {"id": "api_core_014", "question": "How do you handle environment-specific test data, such as different user credentials or seed data per environment?", "expected_answer": "Keep test data external to the code (config/fixtures per environment), or generate it dynamically via setup API calls at test start rather than relying on pre-seeded records that may drift between environments.", "difficulty": "Intermediate", "category": "scenario"},
    {"id": "api_core_015", "question": "Why would you centralize common request setup (base URI, default headers, auth) into a single base request specification rather than repeating it in every test?", "expected_answer": "Reduces duplication and drift - a single place to update auth mechanism, headers, or base URL when the API changes, and ensures every test consistently applies the same baseline configuration.", "difficulty": "Intermediate", "category": "fundamentals"},
    {"id": "api_core_016", "question": "How would you handle API endpoints that differ between environments due to separate microservice URLs (service discovery)?", "expected_answer": "Map logical service names to environment-specific URLs in config, or use a service registry/gateway URL consistently across environments so tests reference logical names, not hard-coded hosts.", "difficulty": "Advanced", "category": "scenario"},
    {"id": "api_core_017", "question": "What is the role of a secrets manager (or .env file) in an API test framework, particularly for credentials and API keys?", "expected_answer": "Keeps sensitive values out of source control and test code, injecting them at runtime from a secure store (Vault, AWS Secrets Manager) or a gitignored .env file loaded by the framework/CI pipeline.", "difficulty": "Intermediate", "category": "tool"},

    # Dynamic content validation
    {"id": "api_core_018", "question": "How do you validate dynamic values in an API response, such as timestamps, UUIDs, or auto-generated IDs that change every run?", "expected_answer": "Assert on format/pattern (regex for UUID, ISO-8601 date format) rather than an exact value, or capture the actual value from the response and use it for subsequent chained assertions instead of hard-coding an expected literal.", "difficulty": "Intermediate", "category": "coding_problem"},
    {"id": "api_core_019", "question": "What is JSON Schema validation, and why would you use it instead of asserting exact field values?", "expected_answer": "JSON Schema describes the expected structure/types/constraints of a response (required fields, data types, formats) - validating against it catches structural regressions without needing to hard-code every dynamic value.", "difficulty": "Intermediate", "category": "tool"},
    {"id": "api_core_020", "question": "How do you validate a response when the order of elements in an array isn't guaranteed?", "expected_answer": "Compare as sets/unordered collections, sort both actual and expected before comparing, or assert on the presence of expected elements individually (containsAll-style) rather than positional equality.", "difficulty": "Intermediate", "category": "coding_problem"},
    {"id": "api_core_021", "question": "How would you chain API requests where a value from one response (e.g. a newly created resource's ID) needs to be used in the next request?", "expected_answer": "Extract the value from the first response (via JSONPath or a client library's parsed object) and store it in a variable/context object passed to the subsequent request, rather than hard-coding an assumed ID.", "difficulty": "Intermediate", "category": "coding_problem"},
    {"id": "api_core_022", "question": "How do you handle validating a response that includes a mix of static and dynamic fields?", "expected_answer": "Validate static fields with exact-match assertions and dynamic fields with format/type/range checks (or by excluding them from a schema/snapshot comparison), rather than treating the whole payload as one opaque blob.", "difficulty": "Intermediate", "category": "coding_problem"},
    {"id": "api_core_023", "question": "What is JSONPath (or JMESPath), and how is it used for extracting/validating values from a JSON response?", "expected_answer": "A query language for navigating and extracting values from JSON documents (e.g. $.data.items[0].id) - lets tests assert on or extract deeply nested/dynamic values without manually walking the parsed object tree.", "difficulty": "Intermediate", "category": "tool"},
    {"id": "api_core_024", "question": "How would you validate that a date/timestamp field in a response falls within an acceptable range rather than matching an exact value?", "expected_answer": "Parse the timestamp and assert it's within a tolerance window of 'now' (e.g. created_at is within the last few seconds), or between an expected start/end bound, instead of comparing to a fixed literal.", "difficulty": "Basic", "category": "coding_problem"},
    {"id": "api_core_025", "question": "How do you test pagination in an API - what would you verify beyond just that the first page loads?", "expected_answer": "Page size limits, total count/total pages metadata, next/prev links or cursor tokens, behavior at the last page (empty next), behavior for out-of-range page numbers, and consistency of results if data changes mid-pagination.", "difficulty": "Advanced", "category": "scenario"},

    # Response validation - body / headers / cookies
    {"id": "api_core_026", "question": "Beyond the status code, what else would you validate in an API response?", "expected_answer": "Response body structure/content, headers (Content-Type, caching, rate-limit, custom headers), cookies, response time/SLA, and that no sensitive data leaks into the payload.", "difficulty": "Basic", "category": "fundamentals"},
    {"id": "api_core_027", "question": "How do you validate response headers, such as Content-Type, Cache-Control, or rate-limit headers?", "expected_answer": "Assert the header exists and matches an expected value/pattern (e.g. Content-Type starts with application/json), and for rate-limit headers assert the remaining-count decrements correctly across successive calls.", "difficulty": "Intermediate", "category": "coding_problem"},
    {"id": "api_core_028", "question": "How do you validate cookies set by an API response, including flags like HttpOnly and Secure?", "expected_answer": "Parse the Set-Cookie header (or use the HTTP client's cookie jar/API) and assert the cookie name/value plus its attributes (HttpOnly, Secure, SameSite, expiry) match expected security requirements.", "difficulty": "Advanced", "category": "coding_problem"},
    {"id": "api_core_029", "question": "What's the difference between validating a response body strictly (exact match) versus partially (subset match), and when would you use each?", "expected_answer": "Strict/exact match catches any unexpected field changes but is brittle against additive, backward-compatible API changes; partial/subset match only checks fields relevant to the test, more resilient but can miss unintended additions/removals - choice depends on how tightly coupled the test should be to the contract.", "difficulty": "Advanced", "category": "scenario"},
    {"id": "api_core_030", "question": "How would you test that sensitive data (passwords, tokens, PII) is never returned in an API response body?", "expected_answer": "Explicitly assert those fields are absent or masked in every response that could plausibly include them (profile responses, list endpoints, error messages/stack traces), as a dedicated security-focused test rather than an incidental check.", "difficulty": "Advanced", "category": "scenario"},
    {"id": "api_core_031", "question": "Why does validating the Content-Type of a request/response matter for test reliability?", "expected_answer": "A mismatched Content-Type can cause silent parsing failures or the server rejecting/misinterpreting the payload - asserting on it catches integration issues that a passing status code alone would miss.", "difficulty": "Intermediate", "category": "fundamentals"},
    {"id": "api_core_032", "question": "How would you test API rate limiting, including validating a 429 Too Many Requests response and its Retry-After header?", "expected_answer": "Send requests exceeding the configured limit in a short window, assert a 429 is eventually returned, and validate the Retry-After (or rate-limit-remaining) header gives a sensible value; also verify the limit resets after the window.", "difficulty": "Advanced", "category": "scenario"},
    {"id": "api_core_033", "question": "How do you validate that error response structures are consistent across different endpoints of the same API?", "expected_answer": "Define a shared error schema (error code, message, correlation/trace ID) and validate every failing endpoint's response conforms to it, rather than trusting each endpoint to hand-roll its own error shape.", "difficulty": "Advanced", "category": "scenario"},

    # Auth / token / session lifecycle
    {"id": "api_core_034", "question": "Walk through the end-to-end flow of authenticating with an API and using the resulting token for subsequent requests.", "expected_answer": "Send credentials to a login/token endpoint, receive an access token (and often a refresh token), attach the access token as a Bearer/Authorization header on every subsequent request, and handle re-authentication when it expires.", "difficulty": "Intermediate", "category": "fundamentals"},
    {"id": "api_core_035", "question": "What's the difference between session-based and token-based (JWT) authentication, and how does that affect test design?", "expected_answer": "Session-based auth relies on a server-side session (usually a cookie referencing server state); token-based auth (JWT) is stateless and self-contained, verified without a server-side lookup. Token-based tests can run in parallel more easily since there's no shared server session state to collide.", "difficulty": "Advanced", "category": "fundamentals"},
    {"id": "api_core_036", "question": "Where and how would you store an authentication token so it can be reused across multiple test cases without re-authenticating every time?", "expected_answer": "Authenticate once in a setup/fixture step (e.g. a suite-level or session-scoped hook), store the token in a shared context/config object or environment variable for the test run's duration, and inject it into each request's headers - avoiding a fresh login per test for both speed and reduced load on the auth service.", "difficulty": "Advanced", "category": "scenario"},
    {"id": "api_core_037", "question": "How do you handle token expiry/refresh in a long-running automated test suite?", "expected_answer": "Track the token's expiry time (or catch a 401 mid-run), and proactively (or reactively) call the refresh-token endpoint to get a new access token, updating the stored token used by subsequent requests without failing the whole suite.", "difficulty": "Advanced", "category": "scenario"},
    {"id": "api_core_038", "question": "In a full CRUD test flow (Create -> Update -> Get -> Delete), how do you ensure the same authentication token/session is used consistently across all four requests, and what could go wrong if it isn't?", "expected_answer": "Authenticate once at the start of the flow, keep that token/session in a shared variable, and pass it explicitly to every request in the chain. If a different token is used mid-flow (e.g. a different user context), later steps could fail with 403/404 (can't see a resource created under a different identity) or, worse, silently operate on the wrong user's data.", "difficulty": "Advanced", "category": "scenario"},
    {"id": "api_core_039", "question": "What's the difference between Basic Auth, API Key, OAuth2, and Bearer Token authentication, and how would you implement each in a test framework?", "expected_answer": "Basic Auth: base64-encoded username:password in the Authorization header. API Key: a static key sent as a header or query param. OAuth2: a token obtained via an authorization flow (client credentials, auth code) then sent as Bearer token. Bearer Token: any opaque or JWT token sent as 'Authorization: Bearer <token>' - each requires a different setup step before the actual test requests.", "difficulty": "Advanced", "category": "fundamentals"},
    {"id": "api_core_040", "question": "How would you securely handle auth credentials/tokens in test code, avoiding hard-coding them or committing them to version control?", "expected_answer": "Load credentials from environment variables, a secrets manager, or a gitignored local config, injected at runtime by the test framework or CI pipeline - never embedded as string literals in test source.", "difficulty": "Intermediate", "category": "fundamentals"},
    {"id": "api_core_041", "question": "What is a refresh token, and how would you design a test to validate the refresh token flow?", "expected_answer": "A longer-lived credential used to obtain a new access token without re-entering user credentials. Test by letting the access token expire (or forcing expiry), calling the refresh endpoint with the refresh token, and asserting a new valid access token is issued and works on a protected endpoint.", "difficulty": "Advanced", "category": "coding_problem"},

    # Realistic / dynamic test data
    {"id": "api_core_042", "question": "Why is using hard-coded static test data risky in API test automation, especially in a shared test environment?", "expected_answer": "Parallel or repeated test runs can collide on the same records (unique constraint violations, stale state from a previous run), making tests flaky and non-reproducible in isolation from each other.", "difficulty": "Intermediate", "category": "fundamentals"},
    {"id": "api_core_043", "question": "How would you generate realistic, unique test data to avoid collisions across parallel test runs?", "expected_answer": "Use a data-generation library (e.g. Faker) combined with run-unique identifiers (timestamps, UUIDs) to produce distinct but realistic-looking data (names, emails, addresses) for every test execution.", "difficulty": "Intermediate", "category": "tool"},
    {"id": "api_core_044", "question": "How do you handle test data cleanup after a test creates a resource via a POST request, particularly in a shared environment?", "expected_answer": "Delete the created resource in a teardown/after-hook (ideally even if the test fails), or tag test-created data so a separate cleanup job can purge it, preventing test data from accumulating and polluting the environment.", "difficulty": "Intermediate", "category": "scenario"},
    {"id": "api_core_045", "question": "How would you design a data-driven approach for testing multiple input combinations against the same API endpoint?", "expected_answer": "Parameterize the test with a data set (valid, boundary, and invalid inputs) driven from a file/array, running the same request/assertion logic once per data row, so new cases are added by extending the data set rather than duplicating test code.", "difficulty": "Intermediate", "category": "coding_problem"},

    # Architect / senior-level scenarios
    {"id": "api_core_046", "question": "How would you design an API test automation strategy for a microservices architecture with 20+ services?", "expected_answer": "Layer the strategy: fast unit/contract tests per service, a smaller set of true integration tests across service boundaries, and a thin layer of critical-path end-to-end tests - avoiding a single monolithic suite that re-tests every service's internals through every other service's API.", "difficulty": "Advanced", "category": "scenario"},
    {"id": "api_core_047", "question": "What is contract testing, and how does it differ from traditional integration/API testing?", "expected_answer": "Contract testing (e.g. Pact) verifies that a consumer and provider agree on the shape of their interaction independently, without spinning up the full dependency chain - catching breaking changes earlier and faster than full integration tests that require every service running together.", "difficulty": "Advanced", "category": "fundamentals"},
    {"id": "api_core_048", "question": "How would you test an API endpoint that triggers an asynchronous background job, where the result is only available later via polling or a webhook?", "expected_answer": "Assert the initial 202-style response and job/status identifier, then poll the status endpoint (with a bounded timeout/backoff) until completion, or stand up a test webhook receiver to capture the callback, before asserting on the final result.", "difficulty": "Advanced", "category": "scenario"},
    {"id": "api_core_049", "question": "How would you test API backward compatibility when introducing a new version?", "expected_answer": "Run the existing consumer test suite (or contract tests) against the new version to confirm old clients still work, verify old response fields remain present/unchanged, and explicitly test both versions in parallel during a migration window.", "difficulty": "Advanced", "category": "scenario"},
    {"id": "api_core_050", "question": "What's your strategy for testing an API's error handling for edge cases like malformed JSON, missing required fields, or unexpected data types?", "expected_answer": "Systematically construct negative test cases per field/type (wrong type, null, missing, oversized, malformed JSON entirely) and assert on the correct status code and a clear, consistent error message rather than a generic 500 or an unhandled exception.", "difficulty": "Advanced", "category": "coding_problem"},
    {"id": "api_core_051", "question": "How would you integrate API tests into a CI/CD pipeline, and what would you run differently for smoke tests vs full regression?", "expected_answer": "Run a small, fast smoke suite (critical happy-path flows) on every commit/PR for quick feedback, and a fuller regression suite (edge cases, negative tests, cross-service flows) on a schedule or before release, keeping pipeline feedback loops fast without sacrificing coverage.", "difficulty": "Advanced", "category": "tool"},
    {"id": "api_core_052", "question": "How do you decide what to mock versus what to test against real downstream services in an API test?", "expected_answer": "Mock unreliable, slow, costly, or hard-to-control external dependencies (third-party APIs, payment gateways) to keep tests fast/deterministic; test against real internal services when validating actual integration behavior matters more than isolation, balancing confidence against speed/flakiness.", "difficulty": "Advanced", "category": "scenario"},
]


RESTASSURED_QUESTIONS: List[Dict] = [
    {"id": "api_ra_001", "question": "What is Rest Assured, and why is it commonly used for API testing in Java?", "expected_answer": "A Java library providing a fluent, BDD-style DSL for testing REST APIs, integrating naturally with JUnit/TestNG and Java's ecosystem (Maven/Gradle, Hamcrest matchers, POJOs).", "difficulty": "Basic", "category": "fundamentals"},
    {"id": "api_ra_002", "question": "Explain the given()-when()-then() syntax in Rest Assured.", "expected_answer": "given() sets up the request (headers, params, body, auth); when() specifies the HTTP action (get/post/put/delete on a path); then() asserts on the response (status code, body, headers) - mirroring BDD's Arrange-Act-Assert structure.", "difficulty": "Basic", "category": "fundamentals"},
    {"id": "api_ra_003", "question": "How do you set a base URI once for all Rest Assured tests instead of repeating it in every test?", "expected_answer": "Set RestAssured.baseURI (and optionally basePath) statically in a base test class or @BeforeClass/@BeforeSuite setup, so individual tests only specify the relative endpoint path.", "difficulty": "Intermediate", "category": "tool"},
    {"id": "api_ra_004", "question": "What is a RequestSpecification and a ResponseSpecification in Rest Assured, and why would you use them?", "expected_answer": "RequestSpecification bundles common request setup (base URI, headers, auth, content type) into a reusable object; ResponseSpecification bundles common response assertions (expected status, content type) - both reduce duplication across many test methods.", "difficulty": "Intermediate", "category": "tool"},
    {"id": "api_ra_005", "question": "How do you extract a value from a JSON response using Rest Assured?", "expected_answer": "Use response.jsonPath().getString('field.path') (or .get('field') with type inference) to navigate the parsed JSON via a JSONPath-style expression.", "difficulty": "Basic", "category": "coding_problem"},
    {"id": "api_ra_006", "question": "How do you validate response status code and response time SLA in the same Rest Assured call?", "expected_answer": ".then().statusCode(200).time(lessThan(2000L)) chains both assertions - status code via statusCode(), response time via time() with a Hamcrest matcher and a time unit.", "difficulty": "Intermediate", "category": "coding_problem"},
    {"id": "api_ra_007", "question": "How do you deserialize a JSON response into a Java POJO in Rest Assured?", "expected_answer": "response.as(MyClass.class) uses the configured object mapper (Jackson/Gson) to deserialize the response body directly into a Java object for type-safe assertions.", "difficulty": "Intermediate", "category": "coding_problem"},
    {"id": "api_ra_008", "question": "How do you serialize a Java object into a JSON request body in Rest Assured?", "expected_answer": "given().contentType(ContentType.JSON).body(myPojoObject) - Rest Assured's configured object mapper automatically serializes the POJO to JSON before sending.", "difficulty": "Intermediate", "category": "coding_problem"},
    {"id": "api_ra_009", "question": "How do you validate a JSON response against a JSON Schema using Rest Assured?", "expected_answer": "Use the json-schema-validator module: .then().assertThat().body(matchesJsonSchemaInClasspath('schema.json')) to validate structure/types without asserting every field individually.", "difficulty": "Advanced", "category": "tool"},
    {"id": "api_ra_010", "question": "How do you pass authentication (Basic Auth, OAuth2, Bearer token) in Rest Assured?", "expected_answer": "given().auth().basic(user, pass) for Basic Auth; given().auth().oauth2(token) or given().header('Authorization', 'Bearer ' + token) for OAuth2/Bearer token requests.", "difficulty": "Intermediate", "category": "coding_problem"},
    {"id": "api_ra_011", "question": "How would you reuse an authentication token across multiple Rest Assured requests without re-authenticating each time?", "expected_answer": "Authenticate once (e.g. in a @BeforeClass/@BeforeSuite), store the token in a static field or a shared RequestSpecification's default header, and reuse that spec/token across all subsequent requests in the suite.", "difficulty": "Advanced", "category": "scenario"},
    {"id": "api_ra_012", "question": "What are Rest Assured filters, and how would you use one to automatically log requests/responses or inject an auth header?", "expected_answer": "Filters intercept requests/responses (implementing the Filter interface) - RequestLoggingFilter/ResponseLoggingFilter log traffic automatically; a custom filter can inject a fresh auth header on every request without repeating it in each test.", "difficulty": "Advanced", "category": "tool"},
    {"id": "api_ra_013", "question": "How do you validate response headers and cookies using Rest Assured assertions?", "expected_answer": ".then().header('Content-Type', containsString('application/json')) for headers; .then().cookie('sessionId', notNullValue()) for cookies, both combinable with Hamcrest matchers.", "difficulty": "Intermediate", "category": "coding_problem"},
    {"id": "api_ra_014", "question": "What's the difference between using Hamcrest matchers versus simple equals-style assertions when validating Rest Assured responses?", "expected_answer": "Hamcrest matchers (equalTo, containsString, greaterThan, hasItems) are composable and give more readable failure messages, and integrate directly into Rest Assured's fluent .body()/.statusCode() assertions rather than requiring separate assertEquals calls.", "difficulty": "Basic", "category": "fundamentals"},
    {"id": "api_ra_015", "question": "How would you handle dynamic path parameters and query parameters in Rest Assured?", "expected_answer": "given().pathParam('id', userId).queryParam('page', 2).when().get('/users/{id}') - Rest Assured substitutes named path params and appends query params automatically.", "difficulty": "Basic", "category": "coding_problem"},
    {"id": "api_ra_016", "question": "How do you configure Rest Assured to work with self-signed SSL certificates in a test environment?", "expected_answer": "given().relaxedHTTPSValidation() disables strict certificate validation for that request, or configure RestAssured.useRelaxedHTTPSValidation() globally - only appropriate for test/staging, never production.", "difficulty": "Advanced", "category": "tool"},
    {"id": "api_ra_017", "question": "How would you integrate Rest Assured tests with TestNG or JUnit for parallel execution and reporting?", "expected_answer": "Use TestNG's parallel='methods'/'classes' config (or JUnit 5's parallel execution) with thread-safe state (avoid static mutable RequestSpecifications shared incorrectly across threads), and a reporting library (Allure/ExtentReports) for output.", "difficulty": "Advanced", "category": "tool"},
    {"id": "api_ra_018", "question": "How do you validate an array in a JSON response using Rest Assured, e.g. checking its size or that all elements match a condition?", "expected_answer": ".then().body('items.size()', equalTo(5)) for size, or .body('items.price', everyItem(greaterThan(0))) to assert a condition holds for every element in the array.", "difficulty": "Intermediate", "category": "coding_problem"},
    {"id": "api_ra_019", "question": "How would you structure a Rest Assured framework for maintainability - POJOs, request builders, base test class, config management?", "expected_answer": "Separate POJOs/DTOs for request/response models, a base test class centralizing RequestSpecification setup, a config layer for environment values, and reusable request builder/helper classes per resource - keeping test methods focused on assertions, not setup boilerplate.", "difficulty": "Advanced", "category": "scenario"},
    {"id": "api_ra_020", "question": "How do you handle multipart/form-data requests, such as a file upload, in Rest Assured?", "expected_answer": "given().multiPart('file', new File(path)).multiPart('field', value).when().post('/upload') - Rest Assured builds a proper multipart body with the file and additional form fields.", "difficulty": "Intermediate", "category": "coding_problem"},
    {"id": "api_ra_021", "question": "How would you chain multiple Rest Assured requests where the response of one becomes the input to the next, e.g. create then update then delete?", "expected_answer": "Extract the created resource's ID via jsonPath() from the POST response, use it as a path parameter in the subsequent PUT/GET/DELETE calls within the same test or a shared test context, keeping the flow linear and dependent on real returned data rather than assumed IDs.", "difficulty": "Advanced", "category": "coding_problem"},
    {"id": "api_ra_022", "question": "How do you log request and response details for debugging a failing Rest Assured test?", "expected_answer": "given().log().all() (or .log().ifValidationFails()) logs the outgoing request; .then().log().all() logs the response - useful during debugging without leaving verbose logging on for every passing test in CI.", "difficulty": "Basic", "category": "tool"},
]


POSTMAN_QUESTIONS: List[Dict] = [
    {"id": "api_pm_001", "question": "What is the difference between a Postman Collection and an Environment?", "expected_answer": "A Collection is a saved, ordered group of requests (and folders) representing an API's endpoints; an Environment is a named set of variables (base URL, credentials) that can be swapped to run the same collection against different targets (dev/QA/prod).", "difficulty": "Basic", "category": "fundamentals"},
    {"id": "api_pm_002", "question": "Explain the different variable scopes in Postman (global, collection, environment, local, data) and their precedence order.", "expected_answer": "From highest to lowest precedence: local (script-only) > data (from a data file during a collection run) > environment > collection > global - a variable defined at a narrower scope overrides the same name at a broader scope.", "difficulty": "Advanced", "category": "fundamentals"},
    {"id": "api_pm_003", "question": "What is the Pre-request Script tab used for in Postman? Give an example use case.", "expected_answer": "JavaScript that runs before the request is sent - commonly used to generate dynamic values (timestamps, signatures), fetch/refresh an auth token, or set a variable computed from other variables.", "difficulty": "Intermediate", "category": "tool"},
    {"id": "api_pm_004", "question": "How do you write assertions in the Postman Tests tab using pm.test()?", "expected_answer": "pm.test('description', function () { pm.expect(pm.response.code).to.eql(200); }) - wraps an assertion (using pm.expect or pm.response helpers) in a named test block that reports pass/fail per assertion.", "difficulty": "Basic", "category": "coding_problem"},
    {"id": "api_pm_005", "question": "How would you extract a value from a response, like an auth token or a created resource's ID, and store it as a variable for a later request?", "expected_answer": "In the Tests tab: const data = pm.response.json(); pm.environment.set('token', data.token); - subsequent requests reference {{token}} in headers/URLs/body.", "difficulty": "Intermediate", "category": "coding_problem"},
    {"id": "api_pm_006", "question": "How do you set up authentication once and reuse it across an entire Postman collection?", "expected_answer": "Configure auth at the collection level (Authorization tab) so every request inherits it by default, or capture a token in an environment variable via a login request's Tests script and reference {{token}} in each request's Authorization header/inherited auth.", "difficulty": "Advanced", "category": "scenario"},
    {"id": "api_pm_007", "question": "What is Newman, and how is it used to run Postman collections in a CI/CD pipeline?", "expected_answer": "A command-line collection runner for Postman - exports the collection/environment as JSON and runs them headlessly (newman run collection.json -e env.json), producing exit codes and reports usable in CI jobs.", "difficulty": "Intermediate", "category": "tool"},
    {"id": "api_pm_008", "question": "How do you parameterize a Postman collection to run against multiple environments?", "expected_answer": "Define separate Environment files (dev.json, qa.json, prod.json) with the same variable names but different values, and select/pass the appropriate environment when running the collection (in the UI or via -e in Newman).", "difficulty": "Intermediate", "category": "tool"},
    {"id": "api_pm_009", "question": "How would you use the Collection Runner (or a CSV/JSON data file) to run the same request with multiple sets of input data?", "expected_answer": "Attach a data file to the Collection Runner (or Newman's -d flag); Postman iterates the collection once per row, exposing each row's columns as data variables ({{columnName}}) inside the requests/scripts.", "difficulty": "Intermediate", "category": "coding_problem"},
    {"id": "api_pm_010", "question": "What is a Postman Mock Server, and when would you use one?", "expected_answer": "A hosted endpoint that returns predefined example responses without a real backend - useful for testing/developing against an API contract before the actual service is implemented, or for isolating tests from a flaky dependency.", "difficulty": "Intermediate", "category": "fundamentals"},
    {"id": "api_pm_011", "question": "How do you validate response status code, headers, and body in the Postman Tests tab?", "expected_answer": "pm.response.to.have.status(200); pm.response.to.have.header('Content-Type'); pm.expect(pm.response.json().field).to.eql(expectedValue); - Postman's chai-based assertion helpers cover all three.", "difficulty": "Basic", "category": "coding_problem"},
    {"id": "api_pm_012", "question": "What is a Postman Monitor, and how would you use it for scheduled API health checks?", "expected_answer": "A scheduled, cloud-run execution of a collection (independent of a local machine) that alerts on failures - used for ongoing production/uptime health checks rather than one-off manual or CI-triggered runs.", "difficulty": "Intermediate", "category": "fundamentals"},
    {"id": "api_pm_013", "question": "How would you design a Postman collection to test a full CRUD flow (Create -> Get -> Update -> Delete) using chained requests and variables?", "expected_answer": "Order the requests as a folder (Create, Get, Update, Delete); the Create request's Tests script saves the new resource's ID to an environment/collection variable, and each subsequent request references {{resourceId}} in its URL, keeping the whole flow dependent on real data from the previous step.", "difficulty": "Advanced", "category": "scenario"},
    {"id": "api_pm_014", "question": "How do you handle sensitive data like API keys or passwords in Postman without exposing them in a shared/exported collection?", "expected_answer": "Store secrets in environment variables marked as 'secret' type (masked in the UI and excluded from collection export by default), never hard-coded directly into request bodies/scripts that get committed or shared.", "difficulty": "Advanced", "category": "scenario"},
    {"id": "api_pm_015", "question": "What's the difference between pm.environment, pm.collectionVariables, and pm.globals in a Postman script?", "expected_answer": "pm.environment reads/writes the currently active Environment's variables; pm.collectionVariables reads/writes variables scoped to the Collection itself (available regardless of active environment); pm.globals reads/writes variables available across all collections/environments.", "difficulty": "Advanced", "category": "fundamentals"},
    {"id": "api_pm_016", "question": "How would you validate a response against a JSON Schema in Postman's Tests tab?", "expected_answer": "Use the ajv library (bundled in Postman's sandbox) or pm.response.to.have.jsonSchema(schema) to validate the parsed response body against a predefined schema object.", "difficulty": "Advanced", "category": "coding_problem"},
    {"id": "api_pm_017", "question": "How do you debug a failing Postman request?", "expected_answer": "Open the Postman Console (View > Show Postman Console) to inspect the raw request/response, headers, and any console.log() output from pre-request/test scripts.", "difficulty": "Basic", "category": "tool"},
    {"id": "api_pm_018", "question": "How would you set up Postman to automatically refresh an expired OAuth2 token before a request?", "expected_answer": "Use a Pre-request Script that checks the stored token's expiry, and if expired, calls the token endpoint synchronously (pm.sendRequest) to get a new token and update the environment variable before the main request executes.", "difficulty": "Advanced", "category": "coding_problem"},
    {"id": "api_pm_019", "question": "What are Postman Folders used for within a collection, and how do folder-level pre-request scripts work?", "expected_answer": "Folders group related requests (e.g. by resource or workflow); a folder-level pre-request script runs before every request inside that folder (in addition to the collection-level one), useful for setup shared by a subset of requests.", "difficulty": "Intermediate", "category": "tool"},
    {"id": "api_pm_020", "question": "How would you organize a large Postman collection for maintainability across many endpoints and multiple testers?", "expected_answer": "Group requests into folders by resource/domain, use consistent naming conventions, centralize shared setup at the collection level, keep environments separate from the collection itself, and use version control (via Postman's Git integration or exported JSON) for collaborative review.", "difficulty": "Advanced", "category": "scenario"},
]


PLAYWRIGHT_API_QUESTIONS: List[Dict] = [
    {"id": "api_pw_001", "question": "How do you perform pure API testing in Playwright without opening a browser?", "expected_answer": "Use Playwright's request fixture (or playwright.request.newContext()) to send HTTP requests directly via an APIRequestContext, entirely independent of launching any browser/page.", "difficulty": "Basic", "category": "fundamentals"},
    {"id": "api_pw_002", "question": "What is APIRequestContext in Playwright, and how do you create one?", "expected_answer": "An isolated HTTP client context (cookies/headers scoped to it) for making API requests - created via request.newContext({baseURL, extraHTTPHeaders}) or used directly through the built-in request fixture in a test.", "difficulty": "Intermediate", "category": "fundamentals"},
    {"id": "api_pw_003", "question": "How do you set a base URL and default headers for all API requests in a Playwright APIRequestContext?", "expected_answer": "Pass baseURL and extraHTTPHeaders options when creating the context: request.newContext({baseURL: 'https://api.example.com', extraHTTPHeaders: {Authorization: 'Bearer ' + token}}) - applied automatically to every request made through that context.", "difficulty": "Intermediate", "category": "tool"},
    {"id": "api_pw_004", "question": "How would you validate the status code and JSON body of a response using Playwright's API testing methods?", "expected_answer": "const response = await request.get('/users/1'); expect(response.status()).toBe(200); const body = await response.json(); expect(body.id).toBe(1); - status(), ok(), and json()/text() are the core response methods.", "difficulty": "Basic", "category": "coding_problem"},
    {"id": "api_pw_005", "question": "How do you send a POST request with a JSON body using Playwright's request context?", "expected_answer": "await request.post('/users', {data: {name: 'Test'}}) - Playwright automatically serializes the 'data' object to JSON and sets the Content-Type header.", "difficulty": "Basic", "category": "coding_problem"},
    {"id": "api_pw_006", "question": "How would you extract and reuse an authentication token across multiple API requests in a Playwright test?", "expected_answer": "Authenticate first, extract the token from the login response's JSON body, then either create a new APIRequestContext with that token in extraHTTPHeaders, or pass an explicit headers option to each subsequent request.", "difficulty": "Advanced", "category": "scenario"},
    {"id": "api_pw_007", "question": "How do you combine UI testing and API testing in the same Playwright test, e.g. using an API call to set up data before a UI test?", "expected_answer": "Use the request fixture to create test data via the API directly (faster/more reliable than doing it through the UI), then navigate the page fixture to the relevant UI screen and continue the test against that seeded state.", "difficulty": "Advanced", "category": "scenario"},
    {"id": "api_pw_008", "question": "How would you validate response headers and cookies using Playwright's API testing capabilities?", "expected_answer": "response.headers() returns a headers object to assert against; response.headersArray() gives raw header entries including duplicates; cookies set via Set-Cookie can be inspected through the context's cookie jar (context.cookies()) if using a context that persists them.", "difficulty": "Advanced", "category": "coding_problem"},
    {"id": "api_pw_009", "question": "What's the advantage of Playwright's built-in API testing over needing a separate library like Axios or node-fetch?", "expected_answer": "One toolchain/config for both UI and API tests, shared context/cookies between API setup and browser-driven flows, consistent reporting/tracing, and no extra dependency to manage or keep in sync with Playwright's own versioning.", "difficulty": "Intermediate", "category": "fundamentals"},
    {"id": "api_pw_010", "question": "How do you handle file upload / multipart form data in a Playwright API request?", "expected_answer": "Pass a multipart option to the request: await request.post('/upload', {multipart: {file: {name: 'file.png', mimeType: 'image/png', buffer: fileBuffer}}}) - Playwright builds the multipart body automatically.", "difficulty": "Intermediate", "category": "coding_problem"},
    {"id": "api_pw_011", "question": "How would you use Playwright's API request context to seed test data before a UI end-to-end test, and clean it up afterward?", "expected_answer": "In a test.beforeEach/fixture, call the API to create the needed resource and store its ID; run the UI test against that seeded state; in an afterEach/fixture teardown, call the API's delete endpoint with the same ID to clean up regardless of test outcome.", "difficulty": "Advanced", "category": "scenario"},
    {"id": "api_pw_012", "question": "How do you validate a JSON Schema for a Playwright API response?", "expected_answer": "Parse the response with response.json(), then validate it against a schema using a library like ajv, since Playwright doesn't have a built-in schema matcher - integrate the check as a regular expect() assertion on the validator's result.", "difficulty": "Advanced", "category": "coding_problem"},
    {"id": "api_pw_013", "question": "How would you configure retries or timeouts for an API request in Playwright?", "expected_answer": "Pass a timeout option per request (request.get(url, {timeout: 5000})), or set a default via the context's constructor; Playwright doesn't auto-retry API requests, so retry logic (backoff, max attempts) needs to be implemented explicitly if required.", "difficulty": "Advanced", "category": "tool"},
    {"id": "api_pw_014", "question": "How do you use storageState with an API-obtained authentication token so a subsequent browser-based test starts already authenticated?", "expected_answer": "Perform the login via the API request context, write the resulting cookies/localStorage into a storageState file (or construct it manually with the token), then load that storageState when creating the browser context for the UI test - skipping a UI-driven login entirely.", "difficulty": "Advanced", "category": "scenario"},
    {"id": "api_pw_015", "question": "How would you test a full CRUD flow (Create, Update, Get, Delete) using only Playwright's API request context, reusing the same auth token across all four calls?", "expected_answer": "Create one authenticated APIRequestContext (or reuse the same headers) for the whole flow; POST to create and capture the returned ID, PUT/PATCH to update using that ID, GET to verify the update, and DELETE using the same ID and token - asserting each step's status/body before proceeding to the next.", "difficulty": "Advanced", "category": "coding_problem"},
    {"id": "api_pw_016", "question": "How do you assert on a dynamic/auto-generated field, like an ID or timestamp, in a Playwright API response?", "expected_answer": "Use expect(value).toMatch(/regex/) for format validation (e.g. a UUID pattern), or capture the value and reuse it in later assertions/requests rather than asserting an exact hard-coded literal.", "difficulty": "Intermediate", "category": "coding_problem"},
    {"id": "api_pw_017", "question": "What's the difference between request.newContext() and using the built-in request fixture directly in a Playwright test?", "expected_answer": "The request fixture is a ready-made APIRequestContext scoped to the test, sharing config from playwright.config.ts (baseURL, etc.); request.newContext() explicitly creates a new, separately configurable context - useful when you need different auth/config than the test's default.", "difficulty": "Advanced", "category": "fundamentals"},
    {"id": "api_pw_018", "question": "How would you debug a failing Playwright API test?", "expected_answer": "Log response.status(), await response.text()/json(), and the request details; Playwright's trace viewer also captures API calls made through the request fixture, viewable alongside any UI actions in the same trace.", "difficulty": "Intermediate", "category": "tool"},
    {"id": "api_pw_019", "question": "How do you handle API rate limiting or throttling (429) responses in a Playwright API test?", "expected_answer": "Check response.status() === 429, read a Retry-After header if present, and implement a bounded wait/retry loop in the test helper rather than letting the test fail outright or looping indefinitely.", "difficulty": "Advanced", "category": "scenario"},
    {"id": "api_pw_020", "question": "How would you structure a Playwright framework to share the same authenticated APIRequestContext across multiple test files?", "expected_answer": "Create a custom fixture (via test.extend) that authenticates once (or reuses a saved storageState/token) and exposes a ready-to-use APIRequestContext to every test file that imports it, avoiding redundant login calls per file.", "difficulty": "Advanced", "category": "scenario"},
]


def is_api_testing_selected(skills: List[str]) -> bool:
    """True when the candidate's skills indicate API testing is relevant -
    an explicit API/API Testing/Rest Assured/Postman skill, or Playwright
    (which commonly includes API testing in its scope)."""
    normalized = {s.strip().lower() for s in (skills or [])}
    triggers = {"api", "api testing", "rest assured", "restassured", "postman", "playwright"}
    return bool(normalized & triggers)


def get_api_testing_questions(count: int, skills: List[str]) -> List[Dict]:
    """
    Select `count` API testing questions, blending the core REST/testing
    fundamentals with tool-specific flavors (Rest Assured, Postman,
    Playwright API testing) based on which skills the candidate selected.
    """
    normalized = {s.strip().lower() for s in (skills or [])}
    has_java = "java" in normalized
    has_playwright = "playwright" in normalized
    has_postman = "postman" in normalized
    has_restassured = bool(normalized & {"rest assured", "restassured"})
    has_api_generic = bool(normalized & {"api", "api testing"})

    flavor_pools = []
    if has_restassured or (has_java and has_api_generic):
        flavor_pools.append(RESTASSURED_QUESTIONS)
    if has_postman:
        flavor_pools.append(POSTMAN_QUESTIONS)
    if has_playwright:
        flavor_pools.append(PLAYWRIGHT_API_QUESTIONS)

    # Blend: roughly half the reservation from core REST/architect-level
    # questions (always relevant regardless of tool), the rest split
    # across whichever tool-specific flavor(s) apply.
    core_target = max(1, count // 2)
    core_selected = random.sample(CORE_API_QUESTIONS, min(core_target, len(CORE_API_QUESTIONS)))

    remaining = max(0, count - len(core_selected))
    flavor_selected: List[Dict] = []
    if flavor_pools:
        per_flavor = max(1, remaining // len(flavor_pools))
        for pool in flavor_pools:
            flavor_selected.extend(random.sample(pool, min(per_flavor, len(pool))))
    else:
        # No specific tool flavor matched (e.g. just "API Testing" typed
        # generically) - fill the remainder from core questions instead.
        extra_needed = remaining
        already_ids = {q["id"] for q in core_selected}
        extra_pool = [q for q in CORE_API_QUESTIONS if q["id"] not in already_ids]
        flavor_selected.extend(random.sample(extra_pool, min(extra_needed, len(extra_pool))))

    combined = core_selected + flavor_selected
    random.shuffle(combined)
    combined = combined[:count]

    questions = []
    for q in combined:
        questions.append({
            "id": q["id"],
            "question": q["question"],
            "expected_answer": q["expected_answer"],
            "section": "API Testing",
            "difficulty": q["difficulty"],
            "category": q["category"],
        })
    return questions
