"""
Playwright (JavaScript/TypeScript) Question Bank
Framework/tooling questions specific to the @playwright/test JS/TS
ecosystem (npm/npx, codegen, fixtures, auto-waiting, etc.). Several of
these don't apply to Playwright-Python or Playwright-Java, so this bank
is only pulled in when the candidate selects Playwright together with
JavaScript or TypeScript.
"""

import random
from typing import Dict, List


PLAYWRIGHT_JS_TS_QUESTIONS: List[Dict] = [
    {"id": "pw_jt_001", "question": "What is Playwright, and why would you choose it over other browser automation tools?", "expected_answer": "A Microsoft-built end-to-end testing/automation framework supporting Chromium, Firefox, and WebKit with a single API. Chosen for auto-waiting, fast/reliable execution, multi-browser/multi-tab support, and built-in tracing/debugging tools.", "difficulty": "Basic", "category": "fundamentals"},
    {"id": "pw_jt_002", "question": "How do you install Playwright and its browser binaries in a project?", "expected_answer": "npm init playwright@latest scaffolds a project; npx playwright install downloads the Chromium/Firefox/WebKit browser binaries Playwright manages independently of system-installed browsers.", "difficulty": "Basic", "category": "tool"},
    {"id": "pw_jt_003", "question": "What are the different ways you can run Playwright tests?", "expected_answer": "npx playwright test (all tests), targeting a file/test name, --project to run a specific browser project, --headed to see the browser, --debug for step-through, or via the VS Code extension/UI mode.", "difficulty": "Basic", "category": "tool"},
    {"id": "pw_jt_004", "question": "How do you generate different types of test reports in Playwright?", "expected_answer": "Configure reporters in playwright.config.ts (list, dot, json, junit, html, or custom) under the 'reporter' option; multiple reporters can run simultaneously.", "difficulty": "Intermediate", "category": "tool"},
    {"id": "pw_jt_005", "question": "What is 'await' and 'async' in Playwright's syntax, and why are almost all Playwright API calls awaited?", "expected_answer": "Playwright's actions (click, fill, navigation) are asynchronous Promises since they involve real browser round-trips; 'async/await' lets test code read sequentially while still waiting for each operation to actually complete before proceeding.", "difficulty": "Basic", "category": "fundamentals"},
    {"id": "pw_jt_006", "question": "What is a Playwright fixture?", "expected_answer": "A mechanism to set up and tear down the environment a test needs (page, context, custom objects) - built-in fixtures like 'page' and 'browser' are injected automatically, and custom fixtures can be defined via test.extend().", "difficulty": "Intermediate", "category": "fundamentals"},
    {"id": "pw_jt_007", "question": "What is the difference between npm and npx?", "expected_answer": "npm installs/manages packages; npx executes a package's binary directly (installing it temporarily if not already present) without requiring a global install - Playwright's CLI is typically invoked via npx.", "difficulty": "Basic", "category": "fundamentals"},
    {"id": "pw_jt_008", "question": "What are the benefits of cross-browser testing with Playwright?", "expected_answer": "Catches browser-specific rendering/JS engine bugs early, ensures consistent user experience across Chromium, Firefox, and WebKit (covering Chrome/Edge, Firefox, and Safari engines) from a single test suite.", "difficulty": "Basic", "category": "fundamentals"},
    {"id": "pw_jt_009", "question": "How do you perform cross-browser testing in Playwright?", "expected_answer": "Define multiple 'projects' in playwright.config.ts, each configured with a different browser (chromium, firefox, webkit); running 'npx playwright test' executes the suite across all configured projects.", "difficulty": "Intermediate", "category": "tool"},
    {"id": "pw_jt_010", "question": "How do you execute Playwright tests in a local (headed) browser for debugging?", "expected_answer": "Run npx playwright test --headed to see the browser UI, or --ui for Playwright's interactive UI mode, or --debug to step through with the Playwright Inspector.", "difficulty": "Basic", "category": "tool"},
    {"id": "pw_jt_011", "question": "How do you open a browser in Playwright, both with and without using a fixture?", "expected_answer": "With the built-in 'page' fixture, Playwright auto-launches the browser/context/page for each test. Without a fixture, you manually call playwright.chromium.launch(), browser.newContext(), and context.newPage() and are responsible for closing them.", "difficulty": "Intermediate", "category": "tool"},
    {"id": "pw_jt_012", "question": "How do you re-run only the failed test cases in Playwright?", "expected_answer": "npx playwright test --last-failed re-runs tests that failed in the previous run, using the .last-run.json file Playwright generates.", "difficulty": "Intermediate", "category": "tool"},
    {"id": "pw_jt_013", "question": "How do you run only a specific test or subset of tests from a suite?", "expected_answer": "Pass a file path/pattern to 'playwright test', use -g '<test name pattern>' to grep by title, or tag tests (e.g. @smoke) and filter with --grep.", "difficulty": "Basic", "category": "tool"},
    {"id": "pw_jt_014", "question": "How do you skip a test conditionally based on the browser being used?", "expected_answer": "Use test.skip(({browserName}) => browserName === 'webkit', 'reason') inside the test, or a conditional at the top of the test body checking the browserName fixture.", "difficulty": "Intermediate", "category": "tool"},
    {"id": "pw_jt_015", "question": "How do you pass and use locators in Playwright?", "expected_answer": "Locators are created via page.locator(selector) or role-based helpers (getByRole, getByText, getByLabel) and represent a way to find element(s) lazily - actions are only resolved against the DOM at the moment they're executed.", "difficulty": "Basic", "category": "tool"},
    {"id": "pw_jt_016", "question": "How do you open a new tab or window in Playwright?", "expected_answer": "Call context.newPage() to open a new tab within the same browser context, or listen for the 'popup' event to capture a tab opened by the application itself (e.g. target=_blank links).", "difficulty": "Intermediate", "category": "tool"},
    {"id": "pw_jt_017", "question": "How do you handle multiple windows or tabs in Playwright?", "expected_answer": "Each tab is its own Page object; listen for context.on('page', handler) to capture new pages/popups as they open, then interact with each Page instance independently.", "difficulty": "Intermediate", "category": "tool"},
    {"id": "pw_jt_018", "question": "How do you handle native browser alerts (alert/confirm/prompt) in Playwright?", "expected_answer": "Register page.on('dialog', async dialog => { ... }) before the action that triggers it, then call dialog.accept() or dialog.dismiss() (optionally passing text for a prompt).", "difficulty": "Intermediate", "category": "tool"},
    {"id": "pw_jt_019", "question": "How do you maximize the browser window in Playwright?", "expected_answer": "Playwright doesn't have a literal 'maximize' API - instead set a large/no viewport via launch options (e.g. viewport: null to use the OS window's actual size, or --start-maximized as a launch arg).", "difficulty": "Intermediate", "category": "tool"},
    {"id": "pw_jt_020", "question": "How do you run Playwright tests in parallel?", "expected_answer": "Playwright parallelizes across files by default using worker processes; configure the 'workers' option in playwright.config.ts, and use test.describe.configure({mode: 'parallel'}) to parallelize within a file too.", "difficulty": "Intermediate", "category": "tool"},
    {"id": "pw_jt_021", "question": "What's the difference between fill() and type() in Playwright?", "expected_answer": "fill() clears the field and sets its value directly (fast, doesn't fire per-key events); type() simulates real keystrokes one at a time, firing keydown/keyup events - needed for JS that reacts to individual key presses (e.g. autocomplete).", "difficulty": "Intermediate", "category": "fundamentals"},
    {"id": "pw_jt_022", "question": "How do you perform hard and soft assertions in Playwright?", "expected_answer": "Hard assertions (expect(x).toBe(y)) throw immediately and stop the test on failure; soft assertions (expect.soft(x).toBe(y)) record the failure but let the test continue, with all failures reported at the end.", "difficulty": "Intermediate", "category": "fundamentals"},
    {"id": "pw_jt_023", "question": "How do you open the Playwright HTML report after a test run?", "expected_answer": "npx playwright show-report opens the generated HTML report (from the 'html' reporter) in a local server/browser window.", "difficulty": "Basic", "category": "tool"},
    {"id": "pw_jt_024", "question": "How do you generate and reuse authentication state (cookies/session) in Playwright?", "expected_answer": "Log in once in a setup project/test, call context.storageState({path: 'auth.json'}) to save cookies/localStorage, then reuse it via storageState in playwright.config.ts or context options so other tests start already authenticated.", "difficulty": "Advanced", "category": "tool"},
    {"id": "pw_jt_025", "question": "What are ARIA options in Playwright locators?", "expected_answer": "getByRole() accepts options like name, exact, checked, pressed, and level to match elements by their accessible role and ARIA attributes, aligning tests with how assistive technology perceives the page.", "difficulty": "Advanced", "category": "fundamentals"},
    {"id": "pw_jt_026", "question": "What is the difference between innerHTML, textContent, and innerText?", "expected_answer": "innerHTML returns the raw HTML markup inside an element; textContent returns all text including hidden elements, ignoring CSS; innerText returns only the visually rendered text, respecting CSS visibility/styling.", "difficulty": "Intermediate", "category": "fundamentals"},
    {"id": "pw_jt_027", "question": "Name a few exceptions/errors you've encountered while working with Playwright.", "expected_answer": "TimeoutError (locator/action didn't resolve in time), Element is not attached to the DOM (stale element after re-render), strict mode violation (locator matched multiple elements), and Target closed/Browser has been closed.", "difficulty": "Intermediate", "category": "scenario"},
    {"id": "pw_jt_028", "question": "How do you take a screenshot in Playwright?", "expected_answer": "await page.screenshot({path: 'file.png'}) for the viewport, or {fullPage: true} to capture the entire scrollable page; locator.screenshot() captures just one element.", "difficulty": "Basic", "category": "tool"},
    {"id": "pw_jt_029", "question": "How do you attach a screenshot to a test reporter in Playwright?", "expected_answer": "Call testInfo.attach('screenshot', {body: buffer, contentType: 'image/png'}) inside the test, or rely on the config's 'screenshot: on/only-on-failure' option which auto-attaches to the HTML report.", "difficulty": "Advanced", "category": "tool"},
    {"id": "pw_jt_030", "question": "How do you save a screenshot to a specific file path in Playwright?", "expected_answer": "Pass an absolute or relative 'path' option to page.screenshot({path: './screenshots/name.png'}) - Playwright creates the file (and directories, in recent versions) at that location.", "difficulty": "Basic", "category": "tool"},
    {"id": "pw_jt_031", "question": "What is the difference between browser.newPage() and context.newPage() / creating a new context?", "expected_answer": "browser.newPage() implicitly creates a new isolated BrowserContext and a page inside it; explicitly creating a context first (browser.newContext()) lets you configure shared settings (storageState, viewport, permissions) once before opening one or more pages within it.", "difficulty": "Advanced", "category": "fundamentals"},
    {"id": "pw_jt_032", "question": "How do you find multiple elements with a single locator in Playwright?", "expected_answer": "locator.all() resolves all matching elements as an array of Locators, or use locator.count() for the match count, and locator.nth(i) to target a specific one - avoids the ambiguity error a strict single-match locator would throw.", "difficulty": "Intermediate", "category": "tool"},
    {"id": "pw_jt_033", "question": "How do you use explicit waits in Playwright?", "expected_answer": "await locator.waitFor({state: 'visible'/'attached'/'hidden'/'detached'}), or page.waitForURL()/waitForResponse() for navigation/network conditions - used on top of Playwright's built-in auto-waiting for less common conditions.", "difficulty": "Intermediate", "category": "tool"},
    {"id": "pw_jt_034", "question": "How would you verify the CSS color of an element in Playwright?", "expected_answer": "Use expect(locator).toHaveCSS('color', 'rgb(255, 0, 0)') which reads the computed style, since CSS colors are normalized to rgb/rgba at runtime regardless of how they were declared (hex, name, etc.).", "difficulty": "Intermediate", "category": "tool"},
    {"id": "pw_jt_035", "question": "What is WebKit in the context of Playwright?", "expected_answer": "The open-source browser engine that powers Safari; Playwright bundles its own build of WebKit so Safari-equivalent behavior can be tested on Windows/Linux/CI without needing an actual Mac.", "difficulty": "Intermediate", "category": "fundamentals"},
    {"id": "pw_jt_036", "question": "What are the key differences between Selenium and Playwright?", "expected_answer": "Playwright has built-in auto-waiting (Selenium needs explicit waits), native multi-tab/multi-context support, faster execution via a persistent browser connection (vs WebDriver's per-command HTTP protocol), and built-in tracing/codegen/network interception.", "difficulty": "Advanced", "category": "fundamentals"},
    {"id": "pw_jt_037", "question": "What are browser contexts in Playwright and why are they useful?", "expected_answer": "A BrowserContext is an isolated, incognito-like session (separate cookies/storage) within a single browser instance - lets tests run in parallel with full isolation without the overhead of launching a new browser per test.", "difficulty": "Advanced", "category": "fundamentals"},
    {"id": "pw_jt_038", "question": "How does Playwright's waiting mechanism (auto-wait) work?", "expected_answer": "Before most actions, Playwright automatically waits for the target element to be attached, visible, stable (not animating), enabled, and able to receive events - removing the need for most manual sleeps or explicit waits.", "difficulty": "Advanced", "category": "fundamentals"},
    {"id": "pw_jt_039", "question": "What are some key debugging tools available in Playwright?", "expected_answer": "Playwright Inspector (--debug), trace viewer (npx playwright show-trace), UI mode (--ui), VS Code extension with live debugging, and page.pause() to freeze execution and inspect state interactively.", "difficulty": "Intermediate", "category": "tool"},
    {"id": "pw_jt_040", "question": "How do you run Codegen in Playwright and what is it used for?", "expected_answer": "npx playwright codegen <url> opens a browser that records your interactions and generates corresponding test code automatically - useful for quickly scaffolding locators and actions.", "difficulty": "Basic", "category": "tool"},
    {"id": "pw_jt_041", "question": "How do you handle authentication in a Playwright test suite so you don't log in on every test?", "expected_answer": "Perform login once in a global setup project, save the authenticated state with context.storageState(), then reference that storage state file in the config so subsequent tests start already logged in.", "difficulty": "Advanced", "category": "tool"},
    {"id": "pw_jt_042", "question": "What is network interception in Playwright and why is it useful?", "expected_answer": "page.route() lets you intercept, modify, mock, block, or inspect network requests/responses - useful for testing error states, mocking slow/unavailable APIs, and asserting on request payloads without needing a real backend.", "difficulty": "Advanced", "category": "fundamentals"},
    {"id": "pw_jt_043", "question": "How do you perform UI/visual regression testing in Playwright?", "expected_answer": "Use expect(page).toHaveScreenshot() (or locator equivalent) which captures a baseline image on first run and pixel-diffs against it on subsequent runs, failing if the visual difference exceeds a configurable threshold.", "difficulty": "Advanced", "category": "tool"},
    {"id": "pw_jt_044", "question": "How do you integrate Playwright tests into a CI/CD pipeline?", "expected_answer": "Install Playwright and browsers in the pipeline (npx playwright install --with-deps), run npx playwright test with the desired reporter, and publish the HTML report/trace artifacts; most CI providers have ready-made Playwright GitHub Actions/templates.", "difficulty": "Intermediate", "category": "tool"},
    {"id": "pw_jt_045", "question": "What are the benefits of running Playwright tests in a CI/CD pipeline?", "expected_answer": "Automated feedback on every commit/PR, consistent headless execution environment, parallelization across CI workers to cut total run time, and artifact capture (traces/screenshots/videos) for failures without needing to reproduce locally.", "difficulty": "Basic", "category": "fundamentals"},
    {"id": "pw_jt_046", "question": "What are some common actions available on a Playwright locator?", "expected_answer": "click(), dblclick(), fill(), type(), check()/uncheck(), selectOption(), hover(), press(), dragTo(), and setInputFiles() for uploads.", "difficulty": "Basic", "category": "tool"},
    {"id": "pw_jt_047", "question": "How do you handle file upload and download in Playwright?", "expected_answer": "Upload: locator.setInputFiles('path/to/file'). Download: listen for the 'download' event (or use page.waitForEvent('download')) around the triggering action, then call download.saveAs() or read download.path().", "difficulty": "Intermediate", "category": "tool"},
    {"id": "pw_jt_048", "question": "How do you compare screenshots for visual differences in Playwright?", "expected_answer": "expect(page).toHaveScreenshot() automatically pixel-diffs against a stored baseline; failures generate an actual/expected/diff image trio for review, and baselines are updated with --update-snapshots.", "difficulty": "Advanced", "category": "tool"},
    {"id": "pw_jt_049", "question": "What built-in report types does Playwright support, and which have you used?", "expected_answer": "list (console output), dot, json, junit (for CI integration), html (interactive browsable report), and blob (for merging sharded runs) - the HTML report is the most commonly used for local debugging with traces/screenshots attached.", "difficulty": "Basic", "category": "tool"},
    {"id": "pw_jt_050", "question": "What types of waits does Playwright support, and how does auto-waiting work?", "expected_answer": "Auto-waiting (built into actions), explicit waits (locator.waitFor, page.waitForSelector/waitForResponse/waitForURL), and timeouts (per-action or global). Auto-wait checks actionability conditions before every interaction so most manual waits become unnecessary.", "difficulty": "Intermediate", "category": "fundamentals"},
    {"id": "pw_jt_051", "question": "What are some best practices for writing efficient and maintainable Playwright tests?", "expected_answer": "Prefer role/text-based locators over brittle CSS/XPath, use Page Object Model for reuse, keep tests independent (no shared state), leverage fixtures for setup/teardown, use storageState to avoid repeated logins, and avoid hard-coded waits/sleeps.", "difficulty": "Advanced", "category": "scenario"},
    {"id": "pw_jt_052", "question": "Explain the Page Object Model in Playwright and how you'd implement it.", "expected_answer": "Encapsulate each page's locators and actions inside a class (e.g. LoginPage with a login() method), so tests call high-level methods instead of duplicating locators/steps - changes to the UI only require updating the page object.", "difficulty": "Intermediate", "category": "tool"},
    {"id": "pw_jt_053", "question": "How do you use fixtures in Playwright to manage test data and setup?", "expected_answer": "Define custom fixtures via test.extend({myFixture: async ({}, use) => { const data = setup(); await use(data); teardown(); }}) so tests declare the fixture as a parameter and get consistent setup/teardown without repeating boilerplate.", "difficulty": "Advanced", "category": "tool"},
    {"id": "pw_jt_054", "question": "How do you handle test data in a Playwright automation framework?", "expected_answer": "Externalize data into JSON/CSV/fixtures or a test-data factory module, generate dynamic data with libraries like faker for isolation between runs, and avoid hard-coding values that make tests brittle or order-dependent.", "difficulty": "Intermediate", "category": "scenario"},
    {"id": "pw_jt_055", "question": "Explain the concept of test retries and how you'd manage them in Playwright.", "expected_answer": "The 'retries' option in playwright.config.ts re-runs a failed test up to N times before marking it failed, useful for masking transient flakiness in CI - but retries should be paired with investigating and fixing genuinely flaky tests, not used to permanently hide bugs.", "difficulty": "Intermediate", "category": "tool"},
    {"id": "pw_jt_056", "question": "How would you structure a Playwright test automation framework from scratch?", "expected_answer": "Organize into page objects/components, reusable fixtures, config-driven environments, a data layer, custom reporters/logging, and a clear separation between test specs and framework utilities - typically pages/, tests/, fixtures/, and utils/ directories.", "difficulty": "Advanced", "category": "scenario"},
    {"id": "pw_jt_057", "question": "How do you manage test environment configurations (dev/QA/staging) in Playwright?", "expected_answer": "Use environment variables (process.env) read into playwright.config.ts, separate config files per environment, or a 'projects' array with different baseURL/use options selected via --project or an env var at runtime.", "difficulty": "Intermediate", "category": "tool"},
    {"id": "pw_jt_058", "question": "How do you troubleshoot a Playwright test failure?", "expected_answer": "Open the trace (npx playwright show-trace) to see a timeline of actions/network/console/DOM snapshots, check the HTML report's screenshots/video, and reproduce locally with --debug or --headed to inspect the exact failure point.", "difficulty": "Intermediate", "category": "scenario"},
    {"id": "pw_jt_059", "question": "How do you handle unexpected errors and exceptions in Playwright tests?", "expected_answer": "Wrap risky operations in try/catch where recovery is meaningful, use test.fail()/test.fixme() to document known-broken tests, assert with clear error messages, and rely on traces/screenshots-on-failure to diagnose root cause rather than swallowing errors silently.", "difficulty": "Advanced", "category": "scenario"},
    {"id": "pw_jt_060", "question": "List some common exceptions/errors you might encounter in Playwright and what causes them.", "expected_answer": "TimeoutError (element never became actionable), strict mode violation (locator matched >1 element when exactly one was expected), Target page/context/browser has been closed (using a page after it closed), and Navigation failed/net::ERR_* (network/navigation issues).", "difficulty": "Intermediate", "category": "fundamentals"},

    # Additional depth so a firm 50+ reservation still has headroom for
    # variety across repeat candidates/sessions.
    {"id": "pw_jt_061", "question": "What is the difference between test.beforeEach and a fixture in Playwright?", "expected_answer": "beforeEach runs imperative setup code before every test in a describe block; fixtures are declarative, reusable, and composable dependencies injected as test arguments, and can be scoped per-test or per-worker unlike beforeEach.", "difficulty": "Advanced", "category": "tool"},
    {"id": "pw_jt_062", "question": "What is the purpose of test.step() in Playwright?", "expected_answer": "Groups a sequence of actions into a named, collapsible step shown in the HTML report/trace, making long tests easier to read and failures easier to localize to a specific logical step.", "difficulty": "Intermediate", "category": "tool"},
    {"id": "pw_jt_063", "question": "How do you emulate a mobile device in Playwright?", "expected_answer": "Use the devices import (e.g. devices['iPhone 13']) spread into browser.newContext(), which configures viewport, user agent, and touch support to match that device profile.", "difficulty": "Intermediate", "category": "tool"},
    {"id": "pw_jt_064", "question": "How do you mock geolocation or grant browser permissions in a Playwright test?", "expected_answer": "Pass geolocation and permissions options to browser.newContext() (e.g. permissions: ['geolocation'], geolocation: {latitude, longitude}) to simulate a location without a real GPS.", "difficulty": "Advanced", "category": "tool"},
    {"id": "pw_jt_065", "question": "How do you mock or stub an API response in Playwright without hitting the real backend?", "expected_answer": "Use page.route(url, route => route.fulfill({status, body})) to intercept matching requests and return a custom response, useful for testing error states or removing backend dependency in tests.", "difficulty": "Advanced", "category": "tool"},
    {"id": "pw_jt_066", "question": "What is the Playwright Trace Viewer and what information does it capture?", "expected_answer": "A visual timeline tool showing DOM snapshots, network activity, console logs, and action-by-action screenshots for a test run, opened via npx playwright show-trace - the primary tool for diagnosing CI failures after the fact.", "difficulty": "Intermediate", "category": "tool"},
    {"id": "pw_jt_067", "question": "What does 'sharding' mean in Playwright, and when would you use it?", "expected_answer": "Splitting the full test suite across multiple machines/CI jobs (--shard=1/3, 2/3, 3/3) so they run concurrently, reducing total wall-clock time for large suites.", "difficulty": "Advanced", "category": "tool"},
    {"id": "pw_jt_068", "question": "How does Playwright's visual comparison threshold work when using toHaveScreenshot()?", "expected_answer": "It supports options like maxDiffPixels and threshold to allow a tolerance for minor rendering differences (anti-aliasing, font rendering) so tests don't fail on imperceptible pixel-level noise.", "difficulty": "Advanced", "category": "tool"},
    {"id": "pw_jt_069", "question": "What is Playwright Component Testing?", "expected_answer": "A mode that mounts and tests individual UI components (React/Vue/Svelte) in a real browser in isolation, rather than testing the whole application end-to-end - bridges unit testing and full E2E testing.", "difficulty": "Advanced", "category": "fundamentals"},
    {"id": "pw_jt_070", "question": "How would you check basic accessibility of a page using Playwright?", "expected_answer": "Use role-based locators (getByRole) which inherently exercise the accessibility tree, and integrate a dedicated library like @axe-core/playwright to run automated accessibility audits within a test.", "difficulty": "Advanced", "category": "tool"},
    {"id": "pw_jt_071", "question": "What environment variables commonly get read into playwright.config.ts, and why?", "expected_answer": "Things like BASE_URL, CI, and credentials - reading them via process.env keeps the config portable across local/CI/multiple environments without hard-coding values into the repo.", "difficulty": "Intermediate", "category": "tool"},
    {"id": "pw_jt_072", "question": "What is the 'webServer' option in playwright.config.ts used for?", "expected_answer": "Automatically starts (and waits for) your application's dev/preview server before running tests, and shuts it down after, so CI doesn't need a separate manual step to boot the app under test.", "difficulty": "Advanced", "category": "tool"},
    {"id": "pw_jt_073", "question": "What does the 'trace: on-first-retry' config option do, and why is it a common default?", "expected_answer": "Only records a full trace when a test fails and gets retried, balancing debuggability against the overhead/storage cost of always tracing every test.", "difficulty": "Advanced", "category": "tool"},
    {"id": "pw_jt_074", "question": "How do you capture and assert on browser console logs in a Playwright test?", "expected_answer": "Listen to page.on('console', msg => ...) to capture log entries as they're emitted, useful for asserting no unexpected errors were logged during a flow.", "difficulty": "Intermediate", "category": "tool"},
    {"id": "pw_jt_075", "question": "How does Playwright handle interacting with elements inside Shadow DOM?", "expected_answer": "Playwright's locators pierce open shadow roots automatically by default (unlike traditional CSS selectors), so most locator strategies work without special shadow-DOM-specific syntax.", "difficulty": "Advanced", "category": "fundamentals"},
    {"id": "pw_jt_076", "question": "What is expect.poll() used for in Playwright?", "expected_answer": "Repeatedly retries a custom assertion against a value that changes over time (e.g. polling a non-DOM condition like an API state) until it matches or the timeout is reached, similar to auto-waiting but for arbitrary conditions.", "difficulty": "Advanced", "category": "tool"},
    {"id": "pw_jt_077", "question": "How would you write a custom matcher/assertion in Playwright?", "expected_answer": "Extend the expect object via expect.extend({...}) with a function returning {pass, message}, allowing reusable custom assertions (e.g. toBeWithinRange) across the test suite.", "difficulty": "Advanced", "category": "tool"},
    {"id": "pw_jt_078", "question": "What is global setup/teardown in Playwright and when would you use it?", "expected_answer": "globalSetup/globalTeardown in the config run once before/after the entire test run (not per test) - useful for seeding a database, starting external services, or generating shared auth state.", "difficulty": "Advanced", "category": "tool"},
    {"id": "pw_jt_079", "question": "How would you simulate multiple simultaneous users interacting with an application in one Playwright test?", "expected_answer": "Create multiple independent BrowserContexts (each with its own storage/cookies) from the same browser, giving each a Page to drive its own user session in parallel within the same test.", "difficulty": "Advanced", "category": "scenario"},
    {"id": "pw_jt_080", "question": "How do you block unnecessary resources (images, fonts, analytics) to speed up Playwright tests?", "expected_answer": "Use page.route() to intercept requests matching certain resource types/URLs and call route.abort(), reducing network overhead and speeding up page loads during test runs.", "difficulty": "Advanced", "category": "tool"},
    {"id": "pw_jt_081", "question": "What is a HAR file and how can Playwright use it for testing?", "expected_answer": "A HAR (HTTP Archive) file records network traffic; Playwright can record one during a real session and later replay it via routeFromHAR(), letting tests run against recorded network responses instead of a live backend.", "difficulty": "Advanced", "category": "tool"},
    {"id": "pw_jt_082", "question": "How do you tag or annotate tests in Playwright (e.g. to mark them as @smoke or @slow)?", "expected_answer": "Add tags in the test title (test('login @smoke', ...)) or use test.info().annotations, then filter runs with --grep '@smoke' to execute only a tagged subset.", "difficulty": "Intermediate", "category": "tool"},
    {"id": "pw_jt_083", "question": "What are 'project dependencies' in Playwright's config, and what problem do they solve?", "expected_answer": "The 'dependencies' field lets one project (e.g. a 'setup' project that logs in and saves auth state) run to completion before dependent projects start, formalizing ordered setup without manual globalSetup scripting.", "difficulty": "Advanced", "category": "tool"},
    {"id": "pw_jt_084", "question": "How do you assert that an element does NOT exist on the page in Playwright?", "expected_answer": "await expect(locator).not.toBeVisible() or .toHaveCount(0) - Playwright auto-retries these negative assertions too, waiting for the element to genuinely be absent rather than checking once.", "difficulty": "Basic", "category": "tool"},
    {"id": "pw_jt_085", "question": "How would you handle a flaky test that fails intermittently only in CI, not locally?", "expected_answer": "Reproduce with the same conditions as CI (headless, resource constraints, same viewport), inspect the trace/video from a failed CI run, and look for timing assumptions or environment-specific differences (fonts, network latency) rather than just adding retries.", "difficulty": "Advanced", "category": "scenario"},
    {"id": "pw_jt_086", "question": "What is the difference between page.waitForLoadState() and Playwright's default auto-waiting?", "expected_answer": "Auto-waiting applies to element actionability before an action; waitForLoadState() explicitly waits for a navigation lifecycle event ('load', 'domcontentloaded', 'networkidle') which is sometimes needed for SPA navigations that don't trigger a full page action.", "difficulty": "Advanced", "category": "tool"},
    {"id": "pw_jt_087", "question": "How do you run a specific Playwright project (e.g. only the 'chromium' project) from the CLI?", "expected_answer": "npx playwright test --project=chromium runs only the tests configured under that named project in playwright.config.ts.", "difficulty": "Basic", "category": "tool"},
    {"id": "pw_jt_088", "question": "What is the difference between locator.click() and dispatching a native click event via evaluate()?", "expected_answer": "locator.click() performs a full actionability check and simulates a real trusted user click; dispatching via evaluate() bypasses actionability/visibility checks and may not reflect how a real user's click would behave.", "difficulty": "Advanced", "category": "tool"},
    {"id": "pw_jt_089", "question": "How would you test drag-and-drop functionality in Playwright?", "expected_answer": "Use locator.dragTo(targetLocator) for a simple case, or compose hover/mouse.down/mouse.move/mouse.up via the low-level mouse API for finer control over intermediate drag steps.", "difficulty": "Intermediate", "category": "tool"},
    {"id": "pw_jt_090", "question": "What's the difference between 'test.describe.serial' and the default parallel test execution in Playwright?", "expected_answer": "test.describe.serial forces tests within that block to run in order in the same worker, stopping the remaining tests if one fails - used when tests share state and must run sequentially, unlike the default independent/parallel execution model.", "difficulty": "Advanced", "category": "tool"},
]


def get_playwright_js_ts_questions(count: int) -> List[Dict]:
    """Select `count` random Playwright(JS/TS) questions for the interview."""
    pool = random.sample(
        PLAYWRIGHT_JS_TS_QUESTIONS, min(count, len(PLAYWRIGHT_JS_TS_QUESTIONS))
    )

    questions = []
    for q in pool:
        questions.append({
            "id": q["id"],
            "question": q["question"],
            "expected_answer": q["expected_answer"],
            "section": "Playwright",
            "difficulty": q["difficulty"],
            "category": q["category"],
        })
    return questions


def is_playwright_selected(skills: List[str]) -> bool:
    """True whenever Playwright is one of the candidate's selected skills,
    regardless of which other language/skill it's paired with."""
    normalized = [s.strip().lower() for s in (skills or [])]
    return "playwright" in normalized
