"""
Universal "Skills Set For All" Question Bank
Questions asked irrespective of the candidate's primary skill selection -
Jenkins/CI-CD, Agile/methodology, general programming/software engineering
practices, framework/architecture explanation, and tricky real-time
scenario questions. Sourced from common themes across current job-site
interview guides (igmGuru, DataCamp, InterviewBit, GeeksforGeeks,
softwaretestingmaterial, Scrum.org forums) rather than any one skill bank.
"""

import random
from typing import Dict, List


UNIVERSAL_SKILLS_QUESTIONS: List[Dict] = [
    # Jenkins & CI/CD Pipeline
    {"id": "univ_001", "question": "What is Jenkins, and what role does it play in a CI/CD pipeline?", "expected_answer": "An open-source automation server that builds, tests, and deploys code automatically on triggers (commits, schedules, webhooks), acting as the orchestration engine for a CI/CD workflow.", "section": "Jenkins/CI-CD", "difficulty": "Basic", "category": "fundamentals"},
    {"id": "univ_002", "question": "What is the difference between Continuous Integration, Continuous Delivery, and Continuous Deployment?", "expected_answer": "CI: merging and testing code changes frequently. Continuous Delivery: code is always in a releasable state after passing the pipeline, but release is manual. Continuous Deployment: every passing change is automatically released to production with no manual gate.", "section": "Jenkins/CI-CD", "difficulty": "Basic", "category": "fundamentals"},
    {"id": "univ_003", "question": "What is a Jenkinsfile, and why use one instead of configuring jobs entirely through the Jenkins UI?", "expected_answer": "A text file defining the pipeline as code, checked into source control - enables versioning, code review, and reuse of pipeline definitions instead of untracked, hard-to-reproduce UI configuration.", "section": "Jenkins/CI-CD", "difficulty": "Intermediate", "category": "fundamentals"},
    {"id": "univ_004", "question": "What is the difference between a Declarative and a Scripted Jenkins pipeline?", "expected_answer": "Declarative uses a structured, opinionated syntax (pipeline { stages { ... } }) that's easier to read/validate; Scripted uses full Groovy syntax, offering more flexibility but requiring more programming expertise.", "section": "Jenkins/CI-CD", "difficulty": "Intermediate", "category": "fundamentals"},
    {"id": "univ_005", "question": "What are Jenkins agents/nodes, and why would you use multiple agents?", "expected_answer": "Agents are worker machines that execute pipeline jobs; using multiple agents distributes load, enables parallel builds, and allows different agents to be configured for specific environments (OS, tools, labels).", "section": "Jenkins/CI-CD", "difficulty": "Intermediate", "category": "tool"},
    {"id": "univ_006", "question": "How do you trigger a Jenkins build automatically when code is committed?", "expected_answer": "Configure a webhook from the source control platform (GitHub/GitLab/Bitbucket) to notify Jenkins on push, or use polling (SCM polling) as a fallback when webhooks aren't available.", "section": "Jenkins/CI-CD", "difficulty": "Basic", "category": "tool"},
    {"id": "univ_007", "question": "What are Jenkins plugins? Name a few you've used or would use.", "expected_answer": "Plugins extend Jenkins's core functionality - common ones include Git, Pipeline, Blue Ocean, Credentials Binding, Docker Pipeline, JUnit/HTML Publisher for reports, and Slack Notification.", "section": "Jenkins/CI-CD", "difficulty": "Basic", "category": "tool"},
    {"id": "univ_008", "question": "How do you handle secrets and credentials securely in a Jenkins pipeline?", "expected_answer": "Use Jenkins's built-in Credentials store (never hard-code secrets in the Jenkinsfile), inject them via withCredentials blocks or credential bindings, and restrict access with role-based permissions.", "section": "Jenkins/CI-CD", "difficulty": "Advanced", "category": "tool"},
    {"id": "univ_009", "question": "What is the difference between a pipeline stage and a step in Jenkins?", "expected_answer": "A stage groups a logical phase of the pipeline (e.g. Build, Test, Deploy) shown as a visual segment in Blue Ocean; a step is an individual task/command executed within a stage.", "section": "Jenkins/CI-CD", "difficulty": "Basic", "category": "fundamentals"},
    {"id": "univ_010", "question": "How would you implement parallel execution in a Jenkins pipeline?", "expected_answer": "Use the 'parallel' block within a stage to run multiple branches (e.g. different test suites or platforms) concurrently, reducing overall pipeline duration.", "section": "Jenkins/CI-CD", "difficulty": "Advanced", "category": "tool"},
    {"id": "univ_011", "question": "How do you integrate automated tests into a Jenkins pipeline so the build fails when tests fail?", "expected_answer": "Run the test command as a pipeline step and publish results with a reporting plugin (e.g. JUnit); a non-zero exit code from the test runner automatically marks that stage/build as failed.", "section": "Jenkins/CI-CD", "difficulty": "Intermediate", "category": "tool"},
    {"id": "univ_012", "question": "What is a webhook, and how does it enable CI/CD automation?", "expected_answer": "An HTTP callback a service (like GitHub) sends to another URL when an event occurs (e.g. a push) - Jenkins/CI tools expose an endpoint that receives this callback to trigger a build without polling.", "section": "Jenkins/CI-CD", "difficulty": "Basic", "category": "fundamentals"},
    {"id": "univ_013", "question": "How do you set up build failure notifications (Slack/email) in a Jenkins pipeline?", "expected_answer": "Use post-build actions/blocks (post { failure { ... } }) with a notification plugin (Slack Notification, Email Extension) to alert the team automatically when a stage fails.", "section": "Jenkins/CI-CD", "difficulty": "Intermediate", "category": "tool"},
    {"id": "univ_014", "question": "What is a build artifact, and how do you archive/publish one in Jenkins?", "expected_answer": "A file produced by the build (compiled binary, test report, coverage output) preserved for later use; archiveArtifacts in a Jenkinsfile stores it against the build for download or downstream pipeline consumption.", "section": "Jenkins/CI-CD", "difficulty": "Intermediate", "category": "tool"},
    {"id": "univ_015", "question": "How would you implement a blue-green or canary deployment strategy in a CI/CD pipeline?", "expected_answer": "Blue-green: deploy the new version alongside the old on separate environments and switch traffic once verified, enabling instant rollback. Canary: gradually shift a small percentage of traffic to the new version, monitoring before a full rollout.", "section": "Jenkins/CI-CD", "difficulty": "Advanced", "category": "scenario"},
    {"id": "univ_016", "question": "What is Jenkins Blue Ocean and what problem does it address?", "expected_answer": "A modernized Jenkins UI that visualizes pipelines as a clear stage-by-stage flow diagram, making it easier to understand pipeline status and diagnose failures compared to the classic UI.", "section": "Jenkins/CI-CD", "difficulty": "Basic", "category": "tool"},
    {"id": "univ_017", "question": "How do you manage environment-specific configuration across dev/QA/prod stages of a pipeline?", "expected_answer": "Externalize config via environment variables, parameterized builds, or per-environment config files/credentials, so the same pipeline definition deploys correctly to each environment without hard-coded values.", "section": "Jenkins/CI-CD", "difficulty": "Advanced", "category": "scenario"},
    {"id": "univ_018", "question": "What is idempotency in CI/CD pipeline design, and why does it matter?", "expected_answer": "Running the same pipeline/deployment multiple times produces the same end state without unintended side effects - critical for safe retries after a partial failure.", "section": "Jenkins/CI-CD", "difficulty": "Advanced", "category": "fundamentals"},
    {"id": "univ_019", "question": "How would you roll back a failed deployment in a CI/CD pipeline?", "expected_answer": "Redeploy the last known-good artifact/image version (kept from a previous successful build), or use platform rollback features (Kubernetes rollout undo, blue-green traffic switch back) rather than trying to manually patch forward.", "section": "Jenkins/CI-CD", "difficulty": "Advanced", "category": "scenario"},
    {"id": "univ_020", "question": "What's the difference between a CI server like Jenkins and a GitOps/CD tool like ArgoCD or Spinnaker?", "expected_answer": "Jenkins focuses on building/testing and orchestrating pipeline steps; GitOps tools continuously reconcile a cluster's actual state to match a declared desired state in Git, specializing in the deployment/delivery side.", "section": "Jenkins/CI-CD", "difficulty": "Advanced", "category": "fundamentals"},

    # Agile / Methodology (general, not QA-specific)
    {"id": "univ_021", "question": "What's the difference between Scrum and Kanban?", "expected_answer": "Scrum works in fixed-length sprints with defined roles/ceremonies and a committed backlog per sprint; Kanban is a continuous-flow method with no fixed iterations, using WIP limits to manage flow instead.", "section": "Agile/Methodology", "difficulty": "Basic", "category": "fundamentals"},
    {"id": "univ_022", "question": "What is the difference between the roles of a Scrum Master and a Product Owner?", "expected_answer": "The Scrum Master facilitates the process, removes impediments, and coaches the team on Agile practices; the Product Owner owns the backlog, prioritizes work, and represents stakeholder/business value.", "section": "Agile/Methodology", "difficulty": "Basic", "category": "fundamentals"},
    {"id": "univ_023", "question": "What is a Sprint Retrospective, and why is a 'no blame' culture emphasized during it?", "expected_answer": "A ceremony where the team reflects on what went well/poorly and how to improve; blame shuts down honest feedback, so retrospectives focus on process and systemic issues rather than individuals.", "section": "Agile/Methodology", "difficulty": "Basic", "category": "fundamentals"},
    {"id": "univ_024", "question": "How do you handle a team member who consistently misses their sprint commitments?", "expected_answer": "Have a private conversation to understand root cause (overcommitment, blockers, unclear scope), address it constructively rather than publicly, and adjust sprint planning/estimation if it's a systemic issue rather than an individual one.", "section": "Agile/Methodology", "difficulty": "Advanced", "category": "scenario"},
    {"id": "univ_025", "question": "What's the difference between Definition of Done and Definition of Ready?", "expected_answer": "Definition of Ready is the criteria a story must meet before entering a sprint (clear requirements, estimated, dependencies known); Definition of Done is the criteria for considering a story fully complete (coded, tested, reviewed, deployed).", "section": "Agile/Methodology", "difficulty": "Intermediate", "category": "fundamentals"},
    {"id": "univ_026", "question": "What is technical debt, and how would you advocate for addressing it within an Agile backlog dominated by feature requests?", "expected_answer": "Shortcuts taken for speed that increase future maintenance cost - advocate by quantifying its impact (slower delivery, more bugs) and negotiating dedicated capacity/stories for it each sprint rather than treating it as free.", "section": "Agile/Methodology", "difficulty": "Advanced", "category": "scenario"},
    {"id": "univ_027", "question": "How would you handle a Product Owner who keeps changing priorities mid-sprint?", "expected_answer": "Protect the sprint commitment by pushing new requests to backlog refinement/next sprint planning, while explaining the cost of context-switching and unfinished work to the PO directly.", "section": "Agile/Methodology", "difficulty": "Advanced", "category": "scenario"},
    {"id": "univ_028", "question": "What is a Scrum of Scrums, and when is it used?", "expected_answer": "A synchronization meeting between representatives of multiple Scrum teams working on the same product, used in scaled Agile (e.g. SAFe, LeSS) to coordinate dependencies and cross-team impediments.", "section": "Agile/Methodology", "difficulty": "Advanced", "category": "fundamentals"},
    {"id": "univ_029", "question": "How do story points differ from time-based (hours/days) estimation?", "expected_answer": "Story points estimate relative complexity/effort/risk rather than absolute time, letting the team's actual velocity (points completed per sprint) calibrate real-world duration instead of relying on inconsistent individual time estimates.", "section": "Agile/Methodology", "difficulty": "Intermediate", "category": "fundamentals"},
    {"id": "univ_030", "question": "What is a WIP (Work In Progress) limit in Kanban, and why does it matter?", "expected_answer": "A cap on how many items can be in a given workflow stage at once - prevents multitasking/context-switching, surfaces bottlenecks quickly, and improves overall flow/throughput.", "section": "Agile/Methodology", "difficulty": "Intermediate", "category": "fundamentals"},
    {"id": "univ_031", "question": "How would you facilitate a retrospective when the team seems disengaged and gives only surface-level feedback?", "expected_answer": "Vary the retrospective format (e.g. Start/Stop/Continue, 4Ls, anonymous input via a tool), ask targeted follow-up questions, and create psychological safety by addressing process issues rather than assigning blame.", "section": "Agile/Methodology", "difficulty": "Advanced", "category": "scenario"},
    {"id": "univ_032", "question": "A project has 20 epics with 100 stories each, and the team's velocity is 35 story points per sprint. If each story averages 5 points, roughly how many sprints will the project take, and what does this estimate ignore?", "expected_answer": "20*100 = 2000 stories * 5 points = 10,000 points / 35 per sprint ~= 286 sprints. This ignores that velocity fluctuates, doesn't account for scope changes, technical debt, dependencies, or team ramp-up/holidays - a strong answer flags those caveats rather than just doing the math.", "section": "Agile/Methodology", "difficulty": "Advanced", "category": "scenario"},
    {"id": "univ_033", "question": "What role should a developer or QA play during backlog grooming/refinement?", "expected_answer": "Clarify ambiguous requirements, flag technical risks/dependencies early, help break down large stories, and contribute to estimation - refinement is where quality/testability concerns should surface before a story is committed to a sprint.", "section": "Agile/Methodology", "difficulty": "Intermediate", "category": "fundamentals"},
    {"id": "univ_034", "question": "How do you handle scope creep within an Agile project?", "expected_answer": "Distinguish genuine scope changes from small clarifications, push new scope through proper backlog prioritization rather than silently absorbing it into the current sprint, and make the trade-off (time/quality/scope) visible to stakeholders.", "section": "Agile/Methodology", "difficulty": "Intermediate", "category": "scenario"},
    {"id": "univ_035", "question": "What's the difference between Extreme Programming (XP) and Scrum?", "expected_answer": "Scrum defines a process/role framework (sprints, roles, ceremonies) without prescribing engineering practices; XP is more prescriptive about engineering practices specifically (pair programming, TDD, continuous integration, simple design).", "section": "Agile/Methodology", "difficulty": "Advanced", "category": "fundamentals"},

    # General Programming / Software Engineering
    {"id": "univ_036", "question": "Why is Git considered a distributed version control system, and how does that differ from a centralized system like SVN?", "expected_answer": "Every clone in Git has a full copy of the repository history, allowing offline commits/branching and no single point of failure; centralized systems require a constant connection to a central server for most operations.", "section": "General Programming", "difficulty": "Basic", "category": "fundamentals"},
    {"id": "univ_037", "question": "What's the difference between git merge and git rebase?", "expected_answer": "merge creates a new commit joining two histories, preserving both branches' commit history as-is; rebase replays your branch's commits on top of another branch, producing a linear history but rewriting commit hashes.", "section": "General Programming", "difficulty": "Intermediate", "category": "fundamentals"},
    {"id": "univ_038", "question": "How do you resolve a merge conflict in Git?", "expected_answer": "Open the conflicted file(s), manually reconcile the conflict markers (<<<<<<<, =======, >>>>>>>) to the intended final content, then stage the file and complete the merge/rebase commit.", "section": "General Programming", "difficulty": "Basic", "category": "tool"},
    {"id": "univ_039", "question": "What's the difference between Git Flow and trunk-based development?", "expected_answer": "Git Flow uses long-lived feature/release/develop branches with a structured merge process; trunk-based development has developers commit small, frequent changes directly to (or short-lived branches off) a single main branch, favoring continuous integration.", "section": "General Programming", "difficulty": "Advanced", "category": "fundamentals"},
    {"id": "univ_040", "question": "What do the SOLID design principles stand for?", "expected_answer": "Single Responsibility, Open/Closed, Liskov Substitution, Interface Segregation, Dependency Inversion - five principles guiding maintainable, extensible object-oriented design.", "section": "General Programming", "difficulty": "Intermediate", "category": "fundamentals"},
    {"id": "univ_041", "question": "What is the Singleton design pattern, and give a real use case.", "expected_answer": "Ensures a class has only one instance with a global access point - commonly used for shared resources like a configuration manager, logger, or connection pool.", "section": "General Programming", "difficulty": "Intermediate", "category": "fundamentals"},
    {"id": "univ_042", "question": "What is the Factory design pattern used for?", "expected_answer": "Encapsulates object creation logic in a dedicated method/class so callers don't need to know the concrete class being instantiated - useful when the exact type to create depends on runtime conditions.", "section": "General Programming", "difficulty": "Intermediate", "category": "fundamentals"},
    {"id": "univ_043", "question": "What is technical debt, and how do you balance addressing it against delivering new features?", "expected_answer": "Shortcuts/compromises made for speed that cost more to fix later - balance by making it visible (tracked as backlog items), tackling it incrementally alongside feature work, and reserving dedicated time before it blocks velocity entirely.", "section": "General Programming", "difficulty": "Intermediate", "category": "scenario"},
    {"id": "univ_044", "question": "How do you approach debugging a production issue that you can't reproduce locally?", "expected_answer": "Gather logs/metrics/traces from the actual failure, check for environment differences (data, config, load, timing), add targeted logging if needed, and form/test hypotheses systematically rather than guessing.", "section": "General Programming", "difficulty": "Advanced", "category": "scenario"},
    {"id": "univ_045", "question": "What do you look for when reviewing someone else's code in a pull request?", "expected_answer": "Correctness and edge cases, readability/naming, test coverage, adherence to conventions, potential performance/security issues, and whether the change's scope matches its stated purpose - framed as constructive, specific feedback.", "section": "General Programming", "difficulty": "Intermediate", "category": "behavioral"},
    {"id": "univ_046", "question": "What's the difference between unit tests, integration tests, and end-to-end tests?", "expected_answer": "Unit tests verify a single function/class in isolation (mocked dependencies); integration tests verify multiple components working together (e.g. service + database); end-to-end tests verify the full system from the user's perspective.", "section": "General Programming", "difficulty": "Basic", "category": "fundamentals"},
    {"id": "univ_047", "question": "What is Big-O notation, and why does it matter when writing code?", "expected_answer": "A way to describe how an algorithm's time/space requirements grow with input size - matters because an inefficient algorithm (e.g. O(n^2) vs O(n log n)) can make code unusably slow at scale even if it's correct.", "section": "General Programming", "difficulty": "Intermediate", "category": "fundamentals"},
    {"id": "univ_048", "question": "What's the general difference between synchronous and asynchronous programming?", "expected_answer": "Synchronous code executes one operation at a time, blocking until each completes; asynchronous code can start an operation and continue other work, being notified/resuming when that operation completes - improving throughput for I/O-bound work.", "section": "General Programming", "difficulty": "Basic", "category": "fundamentals"},
    {"id": "univ_049", "question": "What is a race condition, and how do you generally prevent one?", "expected_answer": "A bug where the outcome depends on the unpredictable timing/order of concurrent operations on shared state - prevented via synchronization (locks/mutexes), atomic operations, or avoiding shared mutable state altogether.", "section": "General Programming", "difficulty": "Intermediate", "category": "fundamentals"},
    {"id": "univ_050", "question": "What makes an API 'RESTful'?", "expected_answer": "Stateless client-server communication over HTTP, resources identified by URLs, standard verbs (GET/POST/PUT/DELETE) mapped to CRUD operations, and representations (usually JSON) transferred between client and server.", "section": "General Programming", "difficulty": "Basic", "category": "fundamentals"},
    {"id": "univ_051", "question": "What's the general difference between SQL and NoSQL databases, and when would you choose one over the other?", "expected_answer": "SQL databases use structured schemas and relations with strong consistency (ACID); NoSQL databases (document/key-value/graph) offer flexible schemas and horizontal scalability, often trading strict consistency for availability/partition tolerance - choice depends on data shape and consistency needs.", "section": "General Programming", "difficulty": "Intermediate", "category": "fundamentals"},
    {"id": "univ_052", "question": "What is a memory leak, and how would you detect one in a long-running application?", "expected_answer": "Memory that's no longer needed but never released, causing usage to grow unbounded over time - detect via memory profilers, heap snapshots taken over time, and monitoring RSS/heap metrics in production for a steady upward trend.", "section": "General Programming", "difficulty": "Advanced", "category": "fundamentals"},
    {"id": "univ_053", "question": "What is dependency injection, and why is it useful?", "expected_answer": "Supplying a class's dependencies from the outside (constructor/setter/framework) rather than having it construct them itself - improves testability (dependencies can be mocked) and decouples components from concrete implementations.", "section": "General Programming", "difficulty": "Advanced", "category": "fundamentals"},
    {"id": "univ_054", "question": "What practices do you follow to write clean, maintainable code?", "expected_answer": "Meaningful naming, small single-purpose functions, avoiding duplication (DRY), consistent formatting/conventions, clear error handling, and writing code for the next reader, not just to make it work once.", "section": "General Programming", "difficulty": "Basic", "category": "behavioral"},
    {"id": "univ_055", "question": "What is the difference between composition and inheritance, and when would you favor one over the other?", "expected_answer": "Inheritance models an 'is-a' relationship by extending a base class; composition models a 'has-a' relationship by embedding other objects. Composition is generally favored for flexibility, avoiding deep/fragile inheritance hierarchies.", "section": "General Programming", "difficulty": "Advanced", "category": "fundamentals"},

    # Framework/Architecture Explanation + Tricky Real-Time Scenarios
    {"id": "univ_056", "question": "Walk me through a test automation framework you've built - what were the key design decisions and why?", "expected_answer": "Should cover: language/tool choice, structure (Page Object Model or similar), data handling, reporting, CI integration, and reasoning behind trade-offs made (e.g. why POM over a flat script structure) - looking for genuine understanding, not memorized buzzwords.", "section": "Framework/Real-Time", "difficulty": "Advanced", "category": "scenario"},
    {"id": "univ_057", "question": "How would you design a test automation framework from scratch for a brand-new project?", "expected_answer": "Start with requirements (browsers/platforms, CI needs, team skill), pick a maintainable structure (Page Objects/components), plan reporting/logging, data management, and CI integration early rather than bolting them on later.", "section": "Framework/Real-Time", "difficulty": "Advanced", "category": "scenario"},
    {"id": "univ_058", "question": "How do you decide between building a custom automation framework versus adopting an existing one (e.g. Playwright Test, Cucumber)?", "expected_answer": "Weigh team familiarity, community support/maintenance burden, feature fit (BDD needs, reporting, parallelism), and long-term maintenance cost of a custom build versus the constraints of an off-the-shelf tool.", "section": "Framework/Real-Time", "difficulty": "Advanced", "category": "scenario"},
    {"id": "univ_059", "question": "Your test framework no longer scales as the suite has grown to thousands of tests and runs take hours - what would you do?", "expected_answer": "Profile to find slow tests/bottlenecks, parallelize execution, split suites by risk/tag for selective runs, remove/rewrite flaky or redundant tests, and consider sharding across CI workers.", "section": "Framework/Real-Time", "difficulty": "Advanced", "category": "scenario"},
    {"id": "univ_060", "question": "Different teams want to extend your shared automation framework in incompatible ways - how do you handle it?", "expected_answer": "Facilitate a discussion to align on a shared extension mechanism (plugins/hooks/interfaces) rather than divergent forks, document conventions, and set up a lightweight review process for framework-level changes.", "section": "Framework/Real-Time", "difficulty": "Advanced", "category": "scenario"},
    {"id": "univ_061", "question": "Your CI pipeline takes 3 hours to run and is blocking releases - how would you speed it up?", "expected_answer": "Parallelize/shard test execution, cache dependencies/build artifacts, split fast smoke tests from slower full regression (running the latter less frequently), and profile the pipeline to remove or optimize the slowest stages.", "section": "Framework/Real-Time", "difficulty": "Advanced", "category": "scenario"},
    {"id": "univ_062", "question": "A critical bug is found in production immediately after a release your tests marked as passing - what do you do?", "expected_answer": "Prioritize the fix/rollback first, then do a blameless root-cause analysis of the gap (missing test coverage, environment difference, flaky test masking a real failure) and add regression coverage to prevent recurrence.", "section": "Framework/Real-Time", "difficulty": "Advanced", "category": "scenario"},
    {"id": "univ_063", "question": "How would you convince a team resistant to adopting test automation to invest in it?", "expected_answer": "Show concrete cost of manual regression (time, missed bugs), start with a small high-value pilot to demonstrate ROI, and involve the team in tool/approach decisions rather than mandating it top-down.", "section": "Framework/Real-Time", "difficulty": "Advanced", "category": "scenario"},
    {"id": "univ_064", "question": "Two team members' Git changes conflict badly and neither wants to resolve it - what do you do?", "expected_answer": "Facilitate a conversation to understand both changes' intent, pair on resolving the conflict together rather than assigning blame, and use the situation to reinforce smaller/more frequent commits going forward.", "section": "Framework/Real-Time", "difficulty": "Intermediate", "category": "scenario"},
    {"id": "univ_065", "question": "How would you design a framework to run tests against multiple environments/browsers with minimal duplication?", "expected_answer": "Externalize environment-specific config (base URLs, credentials) rather than hard-coding, parameterize browser/environment selection via config or CLI flags, and keep test logic environment-agnostic.", "section": "Framework/Real-Time", "difficulty": "Advanced", "category": "scenario"},
    {"id": "univ_066", "question": "Your manager asks you to skip writing tests to meet a deadline - how do you respond?", "expected_answer": "Communicate the risk/trade-off clearly (what could break, cost of fixing later), propose a minimal-risk compromise (cover critical paths only), and document the decision rather than silently skipping quality checks.", "section": "Framework/Real-Time", "difficulty": "Advanced", "category": "scenario"},
    {"id": "univ_067", "question": "How do you keep a growing test suite maintainable so it doesn't become a bottleneck itself?", "expected_answer": "Regularly prune redundant/low-value tests, enforce consistent patterns (Page Objects, fixtures), monitor and fix flaky tests promptly, and treat test code with the same quality standards as production code.", "section": "Framework/Real-Time", "difficulty": "Intermediate", "category": "scenario"},
    {"id": "univ_068", "question": "What questions would you ask before starting to automate testing for a legacy application with no existing tests?", "expected_answer": "What are the highest-risk/most-used flows, what's the current release cadence, what environments/data are available for testing, and what's already known to be fragile - prioritize automation around risk, not just coverage percentage.", "section": "Framework/Real-Time", "difficulty": "Advanced", "category": "scenario"},
    {"id": "univ_069", "question": "You're asked to review a colleague's pull request and strongly disagree with their approach - how do you handle it?", "expected_answer": "Give specific, evidence-based feedback focused on the code/trade-offs rather than the person, ask questions to understand their reasoning first, and escalate to a team discussion if it's a genuine architectural disagreement rather than personal preference.", "section": "Framework/Real-Time", "difficulty": "Intermediate", "category": "behavioral"},
    {"id": "univ_070", "question": "How do you stay current with new tools and practices in your field?", "expected_answer": "Following official docs/release notes for tools in active use, community resources (blogs, conference talks, changelogs), and hands-on experimentation with new features before adopting them in production work.", "section": "Framework/Real-Time", "difficulty": "Basic", "category": "behavioral"},
]


def get_universal_skills_questions(count: int) -> List[Dict]:
    """Select `count` random universal 'Skills Set For All' questions."""
    pool = random.sample(
        UNIVERSAL_SKILLS_QUESTIONS, min(count, len(UNIVERSAL_SKILLS_QUESTIONS))
    )
    return [dict(q) for q in pool]
